module Wanxiangshu.Kernel.ToolCatalog.Params

open Wanxiangshu.Kernel.ToolCatalog
open Wanxiangshu.Kernel.WarnTdd

let private doc tool field = paramDoc tool field
let private coder = doc "coder"
let coderIntents = coder "intents"
let coderTdd = coder "tdd"
let investigatorIntents = doc "investigator" "intents"
let private meditator = doc "meditator"
let meditatorIntent = meditator "intent"
let meditatorFiles = meditator "files"
let browserIntent = doc "browser" "intent"
let private executor = doc "executor"
let executorLanguage = executor "language"
let executorProgram = executor "program"
let executorDeps = executor "dependencies"
let executorTimeout = executor "timeout_type"
let executorMode = executor "mode"
let executorWhatToSummarize = executor "what_to_summarize"
let executorWarn = warnDescription

let warnTddDesc = warnTddDescription
let private fuzzyFind = doc "fuzzy_find"
let fuzzyFindPattern = fuzzyFind "pattern"
let fuzzyFindPath = fuzzyFind "path"
let fuzzyFindLimit = fuzzyFind "limit"
let fuzzyFindIterator = fuzzyFind "iterator"
let private fuzzyGrep = doc "fuzzy_grep"
let fuzzyGrepPattern = fuzzyGrep "pattern"
let fuzzyGrepPath = fuzzyGrep "path"
let fuzzyGrepExclude = fuzzyGrep "exclude"
let fuzzyGrepSearchIgnored = fuzzyGrep "searchIgnored"
let fuzzyGrepCaseSensitive = fuzzyGrep "caseSensitive"
let fuzzyGrepContext = fuzzyGrep "context"
let fuzzyGrepLimit = fuzzyGrep "limit"
let fuzzyGrepIterator = fuzzyGrep "iterator"
let private websearch = doc "websearch"
let websearchQuery = websearch "query"
let websearchNumResults = websearch "numResults"
let websearchWhatToSummarize = websearch "what_to_summarize"
let private webfetch = doc "webfetch"
let webfetchUrl = webfetch "url"
let webfetchExtractMain = webfetch "extract_main"
let webfetchPreferLlmsTxt = webfetch "prefer_llms_txt"
let webfetchPrompt = webfetch "prompt"
let private submitReview = doc "submit_review"
let submitReviewWip = submitReview "wip"
let submitReviewReport = submitReview "report"
let submitReviewAffectedFiles = submitReview "affectedFiles"
let webfetchTimeout = webfetch "timeout"
let private returnReviewer = doc "return_reviewer"
let returnReviewerVerdict = returnReviewer "verdict"
let returnReviewerFeedback = returnReviewer "feedback"
let private read = doc "read"
let readPath = read "path"
let readOffset = read "offset"
let readLimit = read "limit"
let private write = doc "write"
let writeFilePath = write "file_path"
let writeContent = write "content"
