module Wanxiangshu.Kernel.ToolCatalog.Params

open Wanxiangshu.Kernel.ToolCatalog

let private doc tool field =
    match paramDoc tool field with
    | Ok d -> d
    | Error e -> failwith e

let private coder = doc "coder"
let coderIntents = coder "intents"
let coderTdd = coder "tdd"
let inspectorIntents = doc "inspector" "intents"
let browserIntent = doc "browser" "intent"
let private executor = doc "executor"
let executorLanguage = executor "language"
let executorCommand = executor "command"
let executorDeps = executor "dependencies"
let executorTimeout = executor "timeout_type"
let executorWhatToSummarize = executor "what_to_summarize"
let executorMaxBytes = executor "max_bytes"
let private fuzzyFind = doc "fuzzy_find"
let fuzzyFindPattern = fuzzyFind "pattern"
let fuzzyFindPath = fuzzyFind "path"
let fuzzyFindLimit = fuzzyFind "limit"
let private fuzzyGrep = doc "fuzzy_grep"
let fuzzyGrepPattern = fuzzyGrep "pattern"
let fuzzyGrepPath = fuzzyGrep "path"
let fuzzyGrepExclude = fuzzyGrep "exclude"
let fuzzyGrepSearchIgnored = fuzzyGrep "searchIgnored"
let fuzzyGrepCaseSensitive = fuzzyGrep "caseSensitive"
let fuzzyGrepContext = fuzzyGrep "context"
let fuzzyGrepLimit = fuzzyGrep "limit"
let private fuzzyContinue = doc "fuzzy_continue"
let fuzzyContinueIterator = fuzzyContinue "iterator"
let private websearch = doc "websearch"
let websearchQuery = websearch "query"
let websearchNumResults = websearch "numResults"
let websearchWhatToSummarize = websearch "what_to_summarize"
let private webfetch = doc "webfetch"
let webfetchUrl = webfetch "url"
let webfetchExtractMain = webfetch "extract_main"
let webfetchPreferLlmsTxt = webfetch "prefer_llms_txt"
let webfetchPrompt = webfetch "prompt"
let private submitReview = doc "submit_review"
let submitReviewWip = submitReview "wip"
let submitReviewReport = submitReview "report"
let submitReviewAffectedFiles = submitReview "affectedFiles"
let webfetchTimeout = webfetch "timeout"
let private returnReviewer = doc "return_reviewer"
let returnReviewerVerdict = returnReviewer "verdict"
let returnReviewerFeedback = returnReviewer "feedback"
let private read = doc "read"
let readPath = read "path"
let readOffset = read "offset"
let readLimit = read "limit"
let private write = doc "write"
let writeFilePath = write "file_path"
let writeContent = write "content"
