/// Flat catalog of IntegrationTool integration specs (one runner entry per spec).
module Wanxiangshu.Tests.IntegrationToolSpecCatalog

open Fable.Core
open Fable.Core.JsInterop
open Wanxiangshu.Tests.IntegrationCapsSpecs
open Wanxiangshu.Tests.IntegrationKnowledgeGraphPreludeSpecs
open Wanxiangshu.Tests.IntegrationAfterHookSpecs
open Wanxiangshu.Tests.IntegrationMaintenanceSpecs
open Wanxiangshu.Tests.IntegrationSubmitKnowledgeGraphSpecs
open Wanxiangshu.Tests.IntegrationSubmitKnowledgeGraphSpecsAppend
open Wanxiangshu.Tests.IntegrationBookkeeperSpecs
open Wanxiangshu.Tests.IntegrationBookkeeperSpecsMux
open Wanxiangshu.Tests.IntegrationBookkeeperSpecsHint
open Wanxiangshu.Tests.IntegrationToolDefSpecs
open Wanxiangshu.Tests.IntegrationToolDefSpecsMimo
open Wanxiangshu.Tests.IntegrationSubagentSpecs
open Wanxiangshu.Tests.IntegrationMiscSpecs
open Wanxiangshu.Tests.IntegrationMiscSpecsAgent
open Wanxiangshu.Tests.IntegrationMiscSpecsExecutorKg
open Wanxiangshu.Tests.IntegrationMuxPreludeSpecs
open Wanxiangshu.Tests.IntegrationMuxKnowledgeGraphSpecsBookkeeper
open Wanxiangshu.Tests.IntegrationMuxKnowledgeGraphSpecs
open Wanxiangshu.Tests.IntegrationMuxTransformSpecs
open Wanxiangshu.Tests.IntegrationMuxToolSpecs
open Wanxiangshu.Tests.IntegrationMuxToolSpecsTodo
open Wanxiangshu.Tests.IntegrationMuxToolSpecsRead
open Wanxiangshu.Tests.IntegrationMuxToolSpecsHooks
open Wanxiangshu.Tests.IntegrationMuxMethodologySpecs
open Wanxiangshu.Tests.IntegrationMuxReviewSpecs
open Wanxiangshu.Tests.IntegrationMuxReviewPromptSpecs
open Wanxiangshu.Tests.IntegrationToolSetup

let integrationToolSpecs () : (string * (unit -> JS.Promise<unit>)) list =
    let reg = sharedMuxRegistration ()
    [
        "wrapperSpec", fun () -> promise { wrapperSpec reg }
        "computeCountSpec", fun () -> promise { computeCountSpec reg }
        "buildCapsFileReadData", buildCapsFileReadDataSpec
        "capsTransform", capsTransformSpec
        "capsTransformInPlace", capsTransformInPlaceSpec
        "defaultPreludeWithoutCaps", defaultPreludeWithoutCapsSpec
        "capsAndBacklogOrder", capsAndBacklogOrderSpec
        "bookkeeperDoesNotReceiveCaps", bookkeeperDoesNotReceiveCapsSpec
        "compactionDoesNotReceiveCaps", compactionDoesNotReceiveCapsSpec
        "knowledgeGraphPreludeWithoutCaps", knowledgeGraphPreludeWithoutCapsSpec
        "coderReceivesKnowledgeGraphPrelude", coderReceivesKnowledgeGraphPreludeSpec
        "browserDoesNotReceiveKnowledgeGraphPrelude", browserDoesNotReceiveKnowledgeGraphPreludeSpec
        "executorChildSessionWithoutInputAgentDoesNotReceiveKnowledgeGraphPrelude", executorChildSessionWithoutInputAgentDoesNotReceiveKnowledgeGraphPreludeSpec
        "fetchKnowledgeGraphSnapshot", fetchKnowledgeGraphSnapshotSpec
        "afterHookRecordsDirectWrite", afterHookRecordsDirectWriteSpec
        "afterHookSkipsChildSession", afterHookSkipsChildSessionSpec
        "afterHookSkipsFailedTool", afterHookSkipsFailedToolSpec
        "afterHookRecordsCoder", afterHookRecordsCoderSpec
        "afterHookRecordsExecutor", afterHookRecordsExecutorSpec
        "dailyMaintenanceLaunch", dailyMaintenanceLaunchSpec
        "heartbeatTriggersMaintenance", heartbeatTriggersMaintenanceSpec
        "heartbeatMaintenanceUsesParentSession", heartbeatMaintenanceUsesParentSessionSpec
        "heartbeatSchedulesOnlyEarliestDailyWhileAppendRuns", heartbeatSchedulesOnlyEarliestDailyWhileAppendRunsSpec
        "dailyRewriteTriggersNextDaily", dailyRewriteTriggersNextDailySpec
        "submitKnowledgeGraphAppend", submitKnowledgeGraphAppendSpec
        "submitKnowledgeGraphAppendEmpty", submitKnowledgeGraphAppendEmptySpec
        "submitKnowledgeGraphAppendDoesNotTriggerMaintenance", submitKnowledgeGraphAppendDoesNotTriggerMaintenanceSpec
        "submitKnowledgeGraphSchemaAllowsEmpty", submitKnowledgeGraphSchemaAllowsEmptySpec
        "submitKnowledgeGraphDailyRewrite", submitKnowledgeGraphDailyRewriteSpec
        "submitKnowledgeGraphReconstructsJobFromHistory", submitKnowledgeGraphReconstructsJobFromHistorySpec
        "submitKnowledgeGraphRejectsSecondCall", submitKnowledgeGraphRejectsSecondCallSpec
        "bookkeeperLaunchCarriesAiSettings", bookkeeperLaunchCarriesAiSettingsSpec
        "bookkeeperFireAndForget", bookkeeperFireAndForgetSpec
        "websearchTriggersBookkeeper", websearchTriggersBookkeeperSpec
        "webfetchTriggersBookkeeper", webfetchTriggersBookkeeperSpec
        "bookkeeperSessionRegisteredInChildAgentRegistry", bookkeeperSessionRegisteredInChildAgentRegistrySpec
        "bookkeeperAfterHookAddsHintToOutput", bookkeeperAfterHookAddsHintToOutputSpec
        "bookkeeperAfterHookSkipsHintOnNonBookkeepingTool", bookkeeperAfterHookSkipsHintOnNonBookkeepingToolSpec
        "bookkeeperAfterHookSkipsHintOnFailure", bookkeeperAfterHookSkipsHintOnFailureSpec
        "muxBookkeeperAfterHookAddsHintToOutput", muxBookkeeperAfterHookAddsHintToOutputSpec
        "muxToolExecuteAfterTriggersBookkeeper", muxToolExecuteAfterTriggersBookkeeperSpec
        "muxToolExecuteAfterSkipsReadOnlyExecutor", muxToolExecuteAfterSkipsReadOnlyExecutorSpec
        "muxDailyMaintenanceLaunch", muxDailyMaintenanceLaunchSpec
        "muxDailyRewriteTriggersNext", muxDailyRewriteTriggersNextSpec
        "toolDefinition", toolDefinitionSpec
        "toolExecuteBefore", toolExecuteBeforeSpec
        "mimoApplyPatchExecuteBefore", mimoApplyPatchExecuteBeforeSpec
        "mimoTaskExecuteRoundTrip", mimoTaskExecuteRoundTripSpec
        "mimoTaskExecuteNestedReport", mimoTaskExecuteNestedReportSpec
        "mimoTaskExecuteInPlaceStrip", mimoTaskExecuteInPlaceStripSpec
        "mimoTaskExecuteStripsTaskId", mimoTaskExecuteStripsTaskIdSpec
        "mimoTaskDefinitionHandlesZodLikeParameters", mimoTaskDefinitionHandlesZodLikeParametersSpec
        "coderTool", coderToolSpec
        "investigatorTool", investigatorToolSpec
        "muxCoderInvalidIntents", muxCoderInvalidIntentsSpec
        "investigatorToolLateClientInjection", investigatorToolLateClientInjectionSpec
        "writeTool", fun () -> writeToolSpec reg
        "loopCommand", fun () -> loopCommandSpec reg
        "agentConfig", agentConfigSpec
        "bookkeeperAgentConfig", bookkeeperAgentConfigSpec
        "disableMimoMemoryAndCheckpoint", disableMimoMemoryAndCheckpointSpec
        "disableMimoMemoryAndCheckpointPreservesUserAgent", disableMimoMemoryAndCheckpointPreservesUserAgentSpec
        "applyAgentConfigForMimoDisablesWorkflow", applyAgentConfigForMimoDisablesWorkflowSpec
        "pluginConfigHookDisablesMimoMemoryAndCheckpoint", pluginConfigHookDisablesMimoMemoryAndCheckpointSpec
        "executorModeSchema", executorModeSchemaSpec
        "executorRejectsInvalidLanguage", executorRejectsInvalidLanguageSpec
        "executorActor", executorActorSpec
        "knowledgeGraphWorkspaceSerialization", knowledgeGraphWorkspaceSerializationSpec
        "knowledgeGraphPortLockTimeout", knowledgeGraphPortLockTimeoutSpec
        "muxFetchKnowledgeGraphSnapshot", muxFetchKnowledgeGraphSnapshotSpec
        "muxReturnBookkeeperAppend", muxReturnBookkeeperAppendSpec
        "muxReturnBookkeeperNoActiveJob", muxReturnBookkeeperNoActiveJobSpec
        "muxReturnBookkeeperReconstructsJobFromHistory", muxReturnBookkeeperReconstructsJobFromHistorySpec
        "muxReturnBookkeeperAppendDoesNotTriggerMaintenance", muxReturnBookkeeperAppendDoesNotTriggerMaintenanceSpec
        "muxReturnBookkeeperRejectsSecondCall", muxReturnBookkeeperRejectsSecondCallSpec
        "muxDailyRewriteTriggersNext", muxDailyRewriteTriggersNextSpec
        "muxExecutorRwTriggersMaintenance", muxExecutorRwTriggersMaintenanceSpec
        "muxExecutorModeSchema", muxExecutorModeSchemaSpec
        "muxReadToolReturnsContent", muxReadToolReturnsContentSpec
        "muxReadToolListsDirectories", muxReadToolListsDirectoriesSpec
        "muxMessageTransformRegistered", muxMessageTransformRegisteredSpec
        "muxKnowledgeGraphPreludeForManager", muxKnowledgeGraphPreludeForManagerSpec
        "muxKnowledgeGraphPreludeForCoder", muxKnowledgeGraphPreludeForCoderSpec
        "muxNoKnowledgeGraphPreludeForExcludedAgents", muxNoKnowledgeGraphPreludeForExcludedAgentsSpec
        "muxCapsAndKnowledgeGraphPreludeOrder", muxCapsAndKnowledgeGraphPreludeOrderSpec
        "muxSummarization", fun () -> promise { muxSummarizationSpec () }
        "muxSummarizationToolPolicy", fun () -> promise { muxSummarizationToolPolicySpec () }
        "muxTopLevelPolicy", muxTopLevelPolicySpec
        "muxTopLevelDedup", muxTopLevelDedupSpec
        "muxMessagesTransformDedupsRepeatedRead", muxMessagesTransformDedupsRepeatedReadSpec
        "muxMessagesTransformDedupsRepeatedFileRead", muxMessagesTransformDedupsRepeatedFileReadSpec
        "muxMessagesTransformDedupsRepeatedReadForTopLevelExec", muxMessagesTransformDedupsRepeatedReadForTopLevelExecSpec
        "muxMessagesTransformAcceptedSubmitReviewEndsLoop", muxMessagesTransformAcceptedSubmitReviewEndsLoopSpec
        "muxTodoWriteWrapperSchema", muxTodoWriteWrapperSchemaSpec
        "muxTodoWriteCapturesCompletedWorkReport", muxTodoWriteCapturesCompletedWorkReportSpec
        "muxBacklogProjection", muxBacklogProjectionSpec
        "muxExecutorRoCatPrependsWarning", muxExecutorRoCatPrependsWarningSpec
        "muxMeditatorReadsFilesFromCwd", muxMeditatorReadsFilesFromCwdSpec
        "muxSubmitReviewNoActiveReview", muxSubmitReviewNoActiveReviewSpec
        "muxSubmitReviewPromptFormat", muxSubmitReviewPromptFormatSpec
        "muxAgentReportWrapperFormatsVerdict", muxAgentReportWrapperFormatsVerdictSpec
        "muxSubmitReviewUsesRolledBackHistoryTask", muxSubmitReviewUsesRolledBackHistoryTaskSpec
        "muxLoopReviewPromptUsesFrontMatter", muxLoopReviewPromptUsesFrontMatterSpec
        "muxSubmitReviewTwoRoundPassAccepts", muxSubmitReviewTwoRoundPassAcceptsSpec
        "muxSubmitReviewRejectKeepsReviewActive", muxSubmitReviewRejectKeepsReviewActiveSpec
        "muxSubmitReviewDoubleCheckReject", muxSubmitReviewDoubleCheckRejectSpec
        "muxSubmitReviewTerminatedCleansReviewState", muxSubmitReviewTerminatedCleansReviewStateSpec
        "muxSubmitReviewWipSkipsReviewer", muxSubmitReviewWipSkipsReviewerSpec
        "muxSubmitReviewOmittedWipSkipsReviewer", muxSubmitReviewOmittedWipSkipsReviewerSpec
        "muxExecutorFailureDoesNotBookkeep", muxExecutorFailureDoesNotBookkeepSpec
        "muxTodoWriteMethodologySchema", muxTodoWriteMethodologySchemaSpec
        "muxCompactingTransformProjectsBacklog", muxCompactingTransformProjectsBacklogSpec
        "muxCompactingTransformEmitsAnchorPrompt", muxCompactingTransformEmitsAnchorPromptSpec
        "muxToolExecuteAfterSkipsChildWorkspace", muxToolExecuteAfterSkipsChildWorkspaceSpec
        "muxEventHookAbortDeactivatesReview", muxEventHookAbortDeactivatesReviewSpec
        "muxEventHookAbortCleansUpKnowledgeGraphJob", muxEventHookAbortCleansUpKnowledgeGraphJobSpec
        "muxToolExecuteBeforeSetsUiLabel", muxToolExecuteBeforeSetsUiLabelSpec
        "muxSystemTransformClearsOutputLength", muxSystemTransformClearsOutputLengthSpec
    ]