module VibeFs.Tests.MagicTests

open VibeFs.Tests.MagicReplaySpecs
open VibeFs.Tests.MagicProjectionSpecs


let run () =
    replayBacklogOpencodeDoesNotMergeConsecutiveTodoWrite ()
    replayBacklogTest ()
    replayEmpty ()
    replaySkipsEmpty ()
    replayBacklogForMimocodeUsesTask ()
    replayBacklogForMimocodeIgnoresActor ()
    magicSessionCaptureRoundTrip ()
    magicSessionShareReportTableAcrossInstances ()
    magicSessionRestoresMimocodeReportDuringBacklogRebuild ()
    replayBacklogForMimocodeMergesConsecutiveWorkReports ()
    replayBacklogForMimocodeMergesConsecutiveTaskBurst ()
    replayBacklogForMimocodeSplitsBurstsOnGap ()
    replayBacklogForMimocodeIgnoresAssistantTextBetweenTasks ()
    replayBacklogForMimocodeIgnoresReasoningBetweenTasks ()
    replayBacklogForMimocodeSplitsOnOtherToolCall ()
    findFoldRangeTest ()
    findFoldRangeOpencodePerCallMimicodePerBurst ()
    findFoldRangeForMimocodeIgnoresReadOnlyTaskCalls ()
    findFoldRangeForMimocodeRequiresThreeProgressBursts ()
    findFoldRangeForMimocodeUsesLastProgressCallInBurst ()
    findFoldRangeForMimocodeAssistantTextKeepsBurst ()
    projectMagicFolds ()
    projectMagicNoFold ()
    projectMagicForMimocodeUsesTask ()
    projectMagicHidesErrors ()
    projectMagicDropsFoldedUserMessages ()
    projectMagicKeepsReviewInFold ()
    projectMagicPrefixUsesTodoTime ()
    projectMagicPrefixStaysStableWhenGrowing ()
    magicSessionRefreshesBacklog ()
    magicSessionRefreshesBacklogForMimocode ()
    buildBacklogTextTest ()
    buildBacklogTextWithErrorTest ()
