module Wanxiangshu.Tests.OpencodeSessionEventCodecTests

open Wanxiangshu.Tests.OpencodeSessionEventCodecTestsSession

let run () =
    getSessionIDFromPropsPrefersPropsKey ()
    getSessionIDFallsBackToPart ()
    getSessionIDFallsBackToInfo ()
    getSessionIDUsesTopLevelIdForSessionError ()
    getSessionIDLifecycleUsesInfoId ()
    getSessionIDReturnsEmptyWhenAbsent ()
    getSessionIDNonLifecycleSkipsInfoId ()
    getPartsTextEmptyOnNonArray ()
    getPartsTextEmptyOnEmptyArray ()
    getPartsTextConcatsTextParts ()
    getPartsTextSkipsNonStringText ()
    isCompletedAssistantMessageNonAssistant ()
    isCompletedAssistantMessageWithError ()
    isCompletedAssistantMessageTerminalFinish ()
    isCompletedAssistantMessageToolFinishNotTerminal ()
    isCompletedAssistantMessageToolFinishWithTimeCompleted ()
    isCompletedAssistantMessageTimeCompleted ()
    decodeTodosEmptyOnNonArray ()
    decodeTodosDropsTerminalStatus ()
    decodeTodosDropsEmptyContent ()
    recoverOpenTodosFromMessagesEmptyOnNonArray ()
    recoverOpenTodosFromMessagesEmptyWhenNoTaskPart ()
    recoverOpenTodosFromMessagesPicksLatestTaskPart ()
    recoverOpenTodosFromMessagesDropsTerminal ()
    decodeLastAssistantEmptyWhenNoCompletedAssistant ()
    decodeLastAssistantReturnsLastTextAndAgent ()
    decodeLastAssistantFallbackWhenFinishAndTimeMissing ()
    decodeLastAssistantDetectsSyntheticAgent ()
    createPromptBodyWithoutAgent ()
    createPromptBodyWithAgent ()
    shouldSkipNudgeTrueWhenNoToolResult ()
    shouldSkipNudgeFalseWhenToolResultPresent ()
