module Wanxiangshu.Tests.TestsEntriesWanxiangzhen

open Fable.Core
open Wanxiangshu.Tests.TestsTestBody

let private prefix (pairs: (string * (unit -> unit)) list) =
    pairs |> List.map (fun (n, b) -> "Wanxiangzhen." + n, TestBody.Sync b)

let private prefixAsync (pairs: (string * (unit -> JS.Promise<unit>)) list) =
    pairs |> List.map (fun (n, b) -> "Wanxiangzhen." + n, TestBody.Async b)

let wanxiangzhenTestEntries () : (string * TestBody) list =
    prefix (Wanxiangshu.Tests.Wanxiangzhen.CommandHookTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.ConfigReaderTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.CoordinatorOpsTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.DagTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.DynTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.E2eBehaviorCoverageTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.E2eBehaviorGapTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.E2eIntegrationTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.EventCodecTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.EventLogParseTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.EventReplayTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.ExtendedCoordinatorOpsTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.ExtendedFfDecisionTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.FfDecisionTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.GitShellTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.HttpCodecTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.PidMonitorTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.PluginTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.SchedulerTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.SerialQueueTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.SessionIoTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.SlaveSpawnTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.SquadConfigTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.SquadEventLogCodecTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.SquadPromptsTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.SquadUpdateIdAssignTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.TaskTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.SquadTaskTransitionTests.entries ())
    @ prefix (Wanxiangshu.Tests.Wanxiangzhen.SlaveRuntimeTests.entries ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.CoordinatorLifecycleEventLogTests.entries ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.CoordinatorLifecycleTests.entries ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.ExtendedMockE2ePluginTests.entriesAsync ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.ExtendedMockE2eReplayTests.entriesAsync ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.ExtendedMockE2eSchedulerTests.entriesAsync ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.ExtendedMockE2eSlaveHttpTests.entriesAsync ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.ExtendedMockE2eSubmitTests.entriesAsync ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.ExtendedMockE2eTests.entriesAsync ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.MockE2eHttpTests.entriesAsync ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.MockE2eTests.entriesAsync ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.OpencodePluginE2eCancelKillTests.entriesAsync ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.OpencodePluginE2eFlowTests.entriesAsync ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.OpencodePluginE2eHooksTests.entriesAsync ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.OpencodePluginE2eIdTests.entriesAsync ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.OpencodePluginE2eSlaveQueryTests.entriesAsync ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.OpencodePluginE2eTests.entriesAsync ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.SlaveRuntimeTests.entriesAsync ())
    @ prefixAsync (Wanxiangshu.Tests.Wanxiangzhen.SquadEventLogFsTests.entriesAsync ())
