<Project>
  <Import Project="../../Directory.Build.props"/>
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
  </PropertyGroup>
  <ItemGroup Condition="$([System.String]::Copy('$(MSBuildProjectName)').StartsWith('Wanxiangshu.Owner.'))">
    <PackageReference Include="FSharp.Core" Version="10.1.203"/>
    <PackageReference Include="Fable.Core" Version="5.0.0"/>
    <PackageReference Include="FsToolkit.ErrorHandling" Version="5.2.0"/>
    <PackageReference Include="Thoth.Json" Version="10.5.1"/>
  </ItemGroup>
</Project>
