<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <WanxiangshuSemanticOwner>time-capability</WanxiangshuSemanticOwner>
    <WanxiangshuOwnerLocality>process-node-timing-adapter</WanxiangshuOwnerLocality>
    <WanxiangshuOwnerLocalityKind>adapter</WanxiangshuOwnerLocalityKind>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="Wanxiangshu.Owner.intra-participant-parallelism.foundation-taskresult.fsproj"/>
    <ProjectReference Include="Wanxiangshu.Owner.time-capability.foundation-temporal-contract.fsproj"/>
    <Compile Include="Process/NodeTiming.fsi"/>
    <Compile Include="Process/NodeTiming.fs"/>
  </ItemGroup>
</Project>
