<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <WanxiangshuSemanticOwner>distribution</WanxiangshuSemanticOwner>
    <WanxiangshuOwnerLocality>assemblyinfo</WanxiangshuOwnerLocality>
    <WanxiangshuOwnerLocalityKind>contract</WanxiangshuOwnerLocalityKind>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="AssemblyInfo.fsi"/>
    <Compile Include="AssemblyInfo.fs"/>
    <Compile Include="Resources/PackageMetadata.fsi"/>
    <Compile Include="Resources/PackageMetadata.fs"/>
    <Compile Include="Resources/PackageResources.fsi"/>
    <Compile Include="Resources/PackageResources.fs"/>
    <Compile Include="Resources/ProviderResourceBytes.fsi"/>
    <Compile Include="Resources/ProviderResourceBytes.fs"/>
    <Compile Include="Resources/ModelRoutingResource.fsi"/>
    <Compile Include="Resources/ModelRoutingResource.fs"/>
  </ItemGroup>
</Project>
