namespace Wanxiangshu.Sphinx.V2.Runtime

open System
open System.Threading.Tasks
open Wanxiangshu.Sphinx.V2.Core

/// Side-effect ports. Everything in this file is an interface the Runtime consumes and
/// a composition owner supplies; nothing here performs I/O on its own.
///
/// WHAT[sphinx-v2-009]: Core never imports the Host, a provider SDK or an MCP SDK. The
/// Runtime reaches them only through these shapes, which is what lets a test drive the
/// whole inquiry with a recording double while the production composition binds a real
/// adapter.
/// A receipt the store hands back after accepting an append. `Cuts` being non-empty
/// means the canonical integration refused the write, which is a real rejection rather
/// than a transport hiccup.
type AppendReceipt =
    { Cuts: string list
      AcceptedRevision: Revision }

type AppendFault =
    | Rejected of reason: string
    | Conflict of currentRevision: Revision

type Envelope = { EventId: string; Payload: string }

type IEventStorePort =
    /// Append one transition batch as one canonical envelope.
    abstract Append: inquiryId: InquiryId * batch: TransitionBatch -> Task<Result<AppendReceipt, AppendFault>>
    /// All accepted envelopes for one inquiry, in canonical order.
    abstract ReadAll: inquiryId: InquiryId -> Task<Result<Envelope list, string>>
    /// The head revision the store currently accepts writes against.
    abstract TryCurrentRevision: inquiryId: InquiryId -> Task<Revision option>

/// What a Host returns when it actually accepts a dispatch. `DispatchIntentId` is
/// generated by Sphinx; `PhysicalRef` must come from the Host, because it is the handle
/// the Host itself will recognize on a later cancel or query.
type DispatchReceipt =
    { DispatchIntentId: string
      PhysicalRef: string
      Receipt: string }

type PhysicalStatus =
    | Running
    | Succeeded
    | Failed of reason: string
    | Cancelled
    | Unknown

/// The Host port: dispatch, read status, read result, request cancel, reconcile.
type IHostPort =
    abstract Capabilities: unit -> string list

    abstract Dispatch:
        inquiryId: InquiryId * work: WorkSpec * publicEnvelope: JsonEnvelope * privateTicket: JsonEnvelope ->
            Task<Result<DispatchReceipt, string>>

    abstract ReadStatus:
        inquiryId: InquiryId * workId: WorkId * attempt: Attempt * physicalRef: string -> Task<PhysicalStatus>

    abstract ReadResult:
        inquiryId: InquiryId * workId: WorkId * attempt: Attempt * physicalRef: string ->
            Task<Result<string option, string>>

    abstract RequestCancel:
        inquiryId: InquiryId * workId: WorkId * attempt: Attempt * physicalRef: string -> Task<Result<Unit, string>>

    /// Re-open the question "does this dispatch exist?" after a crash window.
    abstract Reconcile: inquiryId: InquiryId * dispatchIntentId: string -> Task<Result<string option, string>>

/// The provider port: it only calls, reports usage, and cancels. It does not own the
/// inquiry and does not run a second opinion round.
type IProviderPort =
    abstract Complete:
        inquiryId: InquiryId * prompt: JsonEnvelope * schemaRef: SchemaRef ->
            Task<Result<string * ProviderUsage, string>>

    abstract Cancel: inquiryId: InquiryId * requestRef: string -> Task<Result<Unit, string>>

/// Digest is behind a port so Core stays free of a Host dependency while the hash
/// remains deterministic across the process.
type IDigestPort =
    abstract Sha256Hex: string -> string

type IClockPort =
    abstract Now: unit -> int64
