module Wanxiangshu.Omp.ReviewTools

open Wanxiangshu.Omp.ReviewToolsRegister

let registerLoopFeatures = ReviewToolsRegister.registerLoopFeatures
let registerInputHandler = ReviewToolsRegister.registerInputHandler