/**
 * OpenCode E2E Behavior Coverage Manifest
 *
 * Tracks coverage level for each functional area.
 * Levels: unit | integration | real-e2e | not-covered
 *
 * Rules:
 * - "real-e2e" tests must start opencode serve via HTTP API and link to an exact test name
 * - "integration" tests may import plugin directly but cannot call it E2E
 * - "not-covered" means no test exists at any level
 */

export type CoverageLevel = 'unit' | 'integration' | 'real-e2e' | 'not-covered';

export interface CoverageEntry {
  id: string;
  description: string;
  level: CoverageLevel;
  spec?: string; // path to spec file
  test?: string; // exact test name within the spec file
  note?: string; // explanation for not-covered or demotions
  priority: 'P0' | 'P1' | 'P2';
}

export const COVERAGE: Record<string, CoverageEntry[]> = {
  bootstrap: [
    { id: "OC-BOOT-001", description: "opencode serve starts with plugin loaded", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-basics.js", priority: "P0", test: "OC-BOOT-001 opencode serve starts with plugin loaded" },
    { id: "OC-BOOT-002", description: "/command lists loop", level: "not-covered", priority: "P0", note: "demoted from real-e2e: no matching spec/test yet" },
    { id: "OC-BOOT-003", description: "LLM request includes all registered tools", level: "not-covered", priority: "P0" },
    { id: "OC-BOOT-004", description: "No plugin = baseline with no custom tools/commands", level: "not-covered", priority: "P0" },
    { id: "OC-BOOT-005", description: "Bad plugin path = stderr diagnostic", level: "not-covered", priority: "P0" },
    { id: "OC-BOOT-006", description: "No AGENTS.md = default config, no crash", level: "not-covered", priority: "P0" },
    { id: "OC-BOOT-007", description: "Valid AGENTS.md config applies", level: "not-covered", priority: "P0" },
    { id: "OC-BOOT-008", description: "Corrupt frontmatter does not load half-config", level: "not-covered", priority: "P0" },
    { id: "OC-BOOT-009", description: "Two independent scenarios = no sharing", level: "not-covered", priority: "P0" },
    { id: "OC-BOOT-010", description: "Restart does not double-register hooks", level: "not-covered", priority: "P0" },
  ],
  schema: [
    { id: "OC-SCHEMA-001", description: "Every tool has non-empty description and valid JSON schema", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-basics.js", priority: "P0", test: "OC-SCHEMA-001 tools have description and valid schema" },
    { id: "OC-SCHEMA-002", description: "Executor schema includes required max_bytes", level: "unit", priority: "P0" },
    { id: "OC-SCHEMA-003", description: "Write tools inject warn_tdd into schema", level: "unit", priority: "P0" },
    { id: "OC-SCHEMA-004", description: "Executor injects warn into schema", level: "unit", priority: "P0" },
    { id: "OC-SCHEMA-005", description: "Subagent tools inject warn_reuse", level: "unit", priority: "P0" },
    { id: "OC-SCHEMA-006", description: "todowrite schema replaced with work backlog schema", level: "unit", priority: "P0" },
    { id: "OC-SCHEMA-007", description: "Missing required params rejected by host before execute", level: "not-covered", priority: "P0" },
    { id: "OC-SCHEMA-008", description: "Control fields deleted in before hook, not in execute", level: "integration", priority: "P0" },
    { id: "OC-SCHEMA-009", description: "After hook args correlate with actual exec params", level: "integration", priority: "P0" },
    { id: "OC-PERM-001", description: "Tool visibility per agent matches permission matrix", level: "unit", priority: "P0" },
    { id: "OC-PERM-002", description: "Forbidden tools absent from agent tool list", level: "unit", priority: "P0" },
    { id: "OC-PERM-003", description: "Permission=deny = zero side effects", level: "not-covered", priority: "P0" },
    { id: "OC-PERM-004", description: "Permission=once = one execution only", level: "not-covered", priority: "P0" },
    { id: "OC-PERM-005", description: "No permission responder = wait, then abortable", level: "not-covered", priority: "P0" },
  ],
  messaging: [
    { id: "OC-MSG-001", description: "System transform contains real work directory", level: "integration", priority: "P0" },
    { id: "OC-MSG-002", description: "Caps prelude in first round", level: "not-covered", priority: "P0", note: "demoted from real-e2e: no matching spec/test yet" },
    { id: "OC-MSG-003", description: "No duplicate Caps injection in same epoch", level: "unit", priority: "P0" },
    { id: "OC-MSG-004", description: "New session gets fresh Caps", level: "not-covered", priority: "P0" },
    { id: "OC-MSG-005", description: "Tool result backfilled into next model context", level: "not-covered", priority: "P0", note: "demoted from real-e2e: no matching spec/test yet" },
    { id: "OC-MSG-006", description: "Tool error backfilled as correct part type", level: "not-covered", priority: "P0" },
    { id: "OC-MSG-007", description: "Unicode, newlines, large output not escaped", level: "not-covered", priority: "P0" },
    { id: "OC-MSG-008", description: "Incomplete tool-call/result pairs dont corrupt messages", level: "unit", priority: "P0" },
    { id: "OC-MSG-009", description: "Control fields not leaked to builtin tools", level: "unit", priority: "P0" },
    { id: "OC-MSG-010", description: "Agent tool filtering scoped per session", level: "not-covered", priority: "P0" },
  ],
  file: [
    { id: "OC-FILE-001", description: "write creates file with exact byte content", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-basics.js", priority: "P0", test: "OC-FILE-001 write creates file with exact bytes" },
    { id: "OC-FILE-002", description: "write overwrites file, no trailing residue", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-basics.js", priority: "P0", test: "OC-FILE-002 write overwrites file with no trailing residue" },
    { id: "OC-FILE-003", description: "write empty file exists with length 0", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-basics.js", priority: "P0", test: "OC-FILE-003 write empty file exists with length 0" },
    { id: "OC-FILE-004", description: "write Unicode preserves UTF-8 bytes", level: "not-covered", priority: "P0" },
    { id: "OC-FILE-005", description: "write multi-line preserves line endings", level: "not-covered", priority: "P0" },
    { id: "OC-FILE-006", description: "read returns real content into next model round", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-basics.js", priority: "P0", test: "OC-FILE-006 read returns real file content" },
    { id: "OC-FILE-007", description: "read missing file produces error part, session continues", level: "not-covered", priority: "P0" },
    { id: "OC-FILE-008", description: "write-then-read proves cross-round consistency", level: "not-covered", priority: "P0" },
    { id: "OC-FILE-009", description: "Missing warn_tdd executes and does not produce criticism", level: "not-covered", priority: "P0", note: "demoted from real-e2e: no matching spec/test yet" },
    { id: "OC-FILE-010", description: "warn_tdd not written to file", level: "not-covered", priority: "P0" },
    { id: "OC-FILE-011", description: "Permission deny = file does not exist", level: "not-covered", priority: "P0" },
    { id: "OC-FILE-012", description: "Two sessions write same relative path correctly", level: "not-covered", priority: "P0" },
  ],
  fuzzy: [
    { id: "OC-FUZZY-001", description: "fuzzy_find returns real matching paths", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-basics.js", priority: "P0", test: "OC-FUZZY-001 fuzzy_find returns real matching paths" },
    { id: "OC-FUZZY-002", description: "No match returns explicit empty result", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-fuzzy-executor.js", priority: "P0", test: "OC-FUZZY-002 No match returns explicit empty result" },
    { id: "OC-FUZZY-003", description: "fuzzy_grep returns file, line number, text", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-basics.js", priority: "P0", test: "OC-FUZZY-003 fuzzy_grep returns file, line, text" },
    { id: "OC-FUZZY-004", description: "Multi-pattern returns chunked results", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-fuzzy-executor.js", priority: "P0", test: "OC-FUZZY-004 Multi-pattern returns chunked results" },
    { id: "OC-FUZZY-005", description: "fuzzy_continue gets next page, no duplicates", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-fuzzy-executor.js", priority: "P0", test: "OC-FUZZY-005 fuzzy_continue gets next page, no duplicates" },
    { id: "OC-FUZZY-006", description: "Iterator exhausted returns completion state", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-fuzzy-executor.js", priority: "P0", test: "OC-FUZZY-006 Iterator exhausted returns completion state" },
    { id: "OC-FUZZY-007", description: "Wrong iterator ID does not read other session data", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-fuzzy-executor.js", priority: "P0", test: "OC-FUZZY-007 Wrong iterator ID does not read other session data" },
    { id: "OC-FUZZY-008", description: "Session deleted cleans up iterator", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-fuzzy-executor.js", priority: "P0", test: "OC-FUZZY-008 Session deleted cleans up iterator" },
  ],
  executor: [
    { id: "OC-EXEC-001", description: "Shell command stdout correct", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-basics.js", priority: "P0", test: "OC-EXEC-001 shell command stdout correct" },
    { id: "OC-EXEC-002", description: "JavaScript command stdout correct", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-basics.js", priority: "P0", test: "OC-EXEC-002 JavaScript command stdout correct" },
    { id: "OC-EXEC-003", description: "Non-zero exit code structured return", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-fuzzy-executor.js", priority: "P0", test: "OC-EXEC-003 Non-zero exit code structured return" },
    { id: "OC-EXEC-004", description: "stderr visible, not conflated with success", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-fuzzy-executor.js", priority: "P0", test: "OC-EXEC-004 stderr visible, not conflated with success" },
    { id: "OC-EXEC-005", description: "cwd points to target workspace", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-fuzzy-executor.js", priority: "P0", test: "OC-EXEC-005 cwd points to target workspace" },
    { id: "OC-EXEC-006", description: "max_bytes truncation works", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-fuzzy-executor.js", priority: "P0", test: "OC-EXEC-006 max_bytes truncation works" },
    { id: "OC-EXEC-007", description: "max_bytes boundary no off-by-one", level: "unit", priority: "P0" },
    { id: "OC-EXEC-008", description: "Missing warn executes and does not produce protocol criticism", level: "integration", priority: "P0" },
    { id: "OC-EXEC-009", description: "Network error converted to domain error", level: "unit", priority: "P0" },
    { id: "OC-EXEC-010", description: "Livelock guard triggers on repeated calls", level: "integration", priority: "P0" },
    { id: "OC-EXEC-011", description: "Permission deny = process not started", level: "not-covered", priority: "P0" },
    { id: "OC-EXEC-012", description: "Session abort terminates long command", level: "not-covered", priority: "P0" },
  ],
  pty: [
    { id: "OC-PTY-001", description: "pty_spawn starts process, returns real session ID", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-pty.js", priority: "P0", test: "OC-PTY-001 pty_spawn starts process and returns session ID" },
    { id: "OC-PTY-002", description: "pty_list shows newly created PTY", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-pty.js", priority: "P0", test: "OC-PTY-002 pty_list shows newly created PTY" },
    { id: "OC-PTY-003", description: "pty_read reads initial output", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-pty.js", priority: "P0", test: "OC-PTY-003 pty_read reads initial output" },
    { id: "OC-PTY-004", description: "pty_write writes stdin, reads response", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-pty.js", priority: "P0", test: "OC-PTY-004 pty_write writes stdin, reads response" },
    { id: "OC-PTY-005", description: "pty_kill = PID no longer alive", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-pty.js", priority: "P0", test: "OC-PTY-005 pty_kill terminates process" },
    { id: "OC-PTY-006", description: "After kill, list no longer reports running", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-pty.js", priority: "P0", test: "OC-PTY-006 After kill, list no longer reports running" },
    { id: "OC-PTY-007", description: "Invalid PTY ID returns error, others unaffected", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-pty.js", priority: "P0", test: "OC-PTY-007 Invalid PTY ID returns error, others unaffected" },
    { id: "OC-PTY-008", description: "Session deleted cleans up its PTYs", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-pty.js", priority: "P0", test: "OC-PTY-008 Session deleted cleans up its PTYs" },
    { id: "OC-PTY-009", description: "Different sessions PTYs isolated", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-pty.js", priority: "P0", test: "OC-PTY-009 Different sessions PTYs isolated" },
    { id: "OC-PTY-010", description: "Permission deny = no child process", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-pty.js", priority: "P0", test: "OC-PTY-010 Permission deny = no child process" },
  ],
  web: [
    { id: "OC-WEB-001", description: "websearch returns title, URL, content", level: "real-e2e", priority: "P0", spec: "e2e/opencode/specs/p0-canary-tests-advanced.js", test: "OC-WEB-001 websearch calls mock endpoint and backfills result" },
    { id: "OC-WEB-002", description: "what_to_summarize enters subagent prompt", level: "not-covered", priority: "P0" },
    { id: "OC-WEB-003", description: "Provider HTTP 500 → tool error", level: "not-covered", priority: "P0" },
    { id: "OC-WEB-004", description: "Malformed search JSON no host crash", level: "not-covered", priority: "P0" },
    { id: "OC-WEB-005", description: "webfetch returns fixture content", level: "not-covered", priority: "P0" },
    { id: "OC-WEB-006", description: "webfetch rejects loopback/private/link-local/metadata", level: "unit", priority: "P0" },
    { id: "OC-WEB-007", description: "Redirect to private still rejected", level: "unit", priority: "P0" },
    { id: "OC-WEB-008", description: "browser starts browser subagent", level: "not-covered", priority: "P0" },
    { id: "OC-WEB-009", description: "Browser subagent can call MCP tools", level: "not-covered", priority: "P0" },
    { id: "OC-WEB-010", description: "MCP result enters browser next LLM round", level: "not-covered", priority: "P0" },
    { id: "OC-WEB-011", description: "Browser final text → parent tool result", level: "not-covered", priority: "P0" },
    { id: "OC-WEB-012", description: "MCP process failure = child + resources cleaned", level: "not-covered", priority: "P0" },
  ],
  subagent: [
    { id: "OC-SUB-001", description: "coder creates real child session", level: "real-e2e", priority: "P0", spec: "e2e/opencode/specs/p0-canary-tests-nudge-sub.js", test: "OC-SUB-001 OC-SUB-005 coder child session round-trip" },
    { id: "OC-SUB-002", description: "Child parentID points to caller", level: "not-covered", priority: "P0" },
    { id: "OC-SUB-003", description: "Child uses coder agent", level: "not-covered", priority: "P0" },
    { id: "OC-SUB-004", description: "Coder prompt includes intent and workdir", level: "not-covered", priority: "P0" },
    { id: "OC-SUB-005", description: "Coder complete = tool result with final output", level: "real-e2e", priority: "P0", spec: "e2e/opencode/specs/p0-canary-tests-nudge-sub.js", test: "OC-SUB-001 OC-SUB-005 coder child session round-trip", note: "covered by OC-SUB-001 test" },
    { id: "OC-SUB-006", description: "Inspector complete real child chain", level: "not-covered", priority: "P0" },
    { id: "OC-SUB-007", description: "Meditator uses specified methodology", level: "not-covered", priority: "P0" },
    { id: "OC-SUB-008", description: "Child tool permissions match role", level: "unit", priority: "P0" },
    { id: "OC-SUB-009", description: "Child empty output triggers continuation/fallback", level: "not-covered", priority: "P0" },
    { id: "OC-SUB-010", description: "Child tool-only finish not early-completed", level: "not-covered", priority: "P0" },
    { id: "OC-SUB-011", description: "Parent abort cancels child", level: "not-covered", priority: "P0" },
    { id: "OC-SUB-012", description: "Child API error returned to parent", level: "not-covered", priority: "P0" },
    { id: "OC-SUB-013", description: "Child create failure no phantom registry", level: "unit", priority: "P0" },
    { id: "OC-SUB-014", description: "Child complete = registry/actor/receipt cleanup", level: "unit", priority: "P0" },
    { id: "OC-SUB-015", description: "Two concurrent child results not swapped", level: "unit", priority: "P0" },
  ],
  continue: [
    { id: "OC-CONT-001", description: "First subagent returns continuation handle", level: "integration", priority: "P0" },
    { id: "OC-CONT-002", description: "Continue before child completion = still-running", level: "integration", priority: "P0" },
    { id: "OC-CONT-003", description: "Continue after child completion = next segment", level: "integration", priority: "P0" },
    { id: "OC-CONT-004", description: "Final page returns completion state", level: "integration", priority: "P0" },
    { id: "OC-CONT-005", description: "Repeated final page idempotent", level: "unit", priority: "P0" },
    { id: "OC-CONT-006", description: "Invalid continuation ID fails explicitly", level: "unit", priority: "P0" },
    { id: "OC-CONT-007", description: "Other session cannot consume continuation", level: "unit", priority: "P0" },
    { id: "OC-CONT-008", description: "Session deleted invalidates continuation", level: "not-covered", priority: "P0" },
    { id: "OC-CONT-009", description: "Parent abort during continue does not revive", level: "not-covered", priority: "P0" },
    { id: "OC-CONT-010", description: "Host restart recovery of continuation", level: "not-covered", priority: "P0" },
  ],
  review: [
    { id: "OC-REV-001", description: "/loop task returns With-Review activated", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-advanced.js", priority: "P0", test: "OC-REV-001 /loop task activates review mode" },
    { id: "OC-REV-002", description: "loop_activated appended once", level: "not-covered", priority: "P0", note: "demoted from real-e2e: no matching spec/test yet" },
    { id: "OC-REV-003", description: "Event sessionID, task, generation correct", level: "not-covered", priority: "P0", note: "demoted from real-e2e: no matching spec/test yet" },
    { id: "OC-REV-004", description: "Second /loop returns already active", level: "not-covered", priority: "P0", note: "demoted from real-e2e: no matching spec/test yet" },
    { id: "OC-REV-005", description: "Empty /loop cancels, appends loop_cancelled", level: "not-covered", priority: "P0", note: "demoted from real-e2e: no matching spec/test yet" },
    { id: "OC-REV-006", description: "submit_review with no active loop rejected", level: "not-covered", priority: "P0" },
    { id: "OC-REV-007", description: "submit_review creates real reviewer child session", level: "not-covered", priority: "P0" },
    { id: "OC-REV-008", description: "Reviewer only exposes allowed tools", level: "unit", priority: "P0" },
    { id: "OC-REV-009", description: "affectedFiles and report in reviewer prompt", level: "unit", priority: "P0" },
    { id: "OC-REV-010", description: "First PERFECT double-check semantics", level: "unit", priority: "P0" },
    { id: "OC-REV-011", description: "Second PERFECT ends review", level: "unit", priority: "P0" },
    { id: "OC-REV-012", description: "REVISE feedback → parent session, loop stays active", level: "unit", priority: "P0" },
    { id: "OC-REV-013", description: "Invalid verdict does not end review", level: "unit", priority: "P0" },
    { id: "OC-REV-014", description: "Reviewer empty output → nudge, limit reached → terminate", level: "not-covered", priority: "P0" },
    { id: "OC-REV-015", description: "submit_review wip=true does not complete task", level: "not-covered", priority: "P0" },
    { id: "OC-REV-016", description: "Parent abort during review cancels reviewer", level: "not-covered", priority: "P0" },
    { id: "OC-REV-017", description: "Concurrent submit_review single lock", level: "unit", priority: "P0" },
    { id: "OC-REV-018", description: "Restart recovers active review from NDJSON", level: "not-covered", priority: "P0" },
    { id: "OC-REV-019", description: "After accepted, restart keeps inactive", level: "not-covered", priority: "P0" },
    { id: "OC-REV-020", description: "NDJSON append failure does not mutate memory first", level: "unit", priority: "P0" },
  ],
  nudge: [
    { id: "OC-NUDGE-001", description: "Active loop + stop + incomplete work → nudge", level: "real-e2e", priority: "P0", spec: "e2e/opencode/specs/p0-canary-tests-nudge-sub.js", test: "OC-NUDGE-001 nudge fires exactly once after human turn completed" },
    { id: "OC-NUDGE-002", description: "Nudge text matches current protocol", level: "integration", priority: "P0" },
    { id: "OC-NUDGE-003", description: "Repeated idle does not double-nudge", level: "integration", priority: "P0" },
    { id: "OC-NUDGE-004", description: "Abort finish suppresses nudge", level: "integration", priority: "P0" },
    { id: "OC-NUDGE-005", description: "Stream-abort suppresses late idle", level: "not-covered", priority: "P0" },
    { id: "OC-NUDGE-006", description: "No assistant text + loop active still nudges", level: "integration", priority: "P0" },
    { id: "OC-NUDGE-007", description: "Missing finish field infers from evidence", level: "integration", priority: "P0" },
    { id: "OC-NUDGE-008", description: "All todos complete = no work nudge", level: "unit", priority: "P0" },
    { id: "OC-NUDGE-009", description: "Rejected review triggers revision nudge", level: "integration", priority: "P0" },
    { id: "OC-NUDGE-010", description: "Nudge nonce = system message, no new human turn", level: "not-covered", priority: "P0" },
    { id: "OC-NUDGE-011", description: "Nudge send failure = event, retryable", level: "not-covered", priority: "P0" },
    { id: "OC-NUDGE-012", description: "Two sessions nudge dedup isolated", level: "not-covered", priority: "P0" },
    { id: "OC-NUDGE-013", description: "Session deleted cleans nudge runtime", level: "not-covered", priority: "P0" },
    { id: "OC-NUDGE-014", description: "Force-stop late events do not revive nudge", level: "unit", priority: "P0" },
    { id: "OC-NUDGE-015", description: "idle→error vs error→idle give consistent result", level: "unit", priority: "P0" },
  ],
  fallback: [
    { id: "OC-FB-001", description: "Empty output → single zero-width char injection", level: "integration", priority: "P0" },
    { id: "OC-FB-002", description: "Injection = zero-width char, not XML", level: "integration", priority: "P0" },
    { id: "OC-FB-003", description: "Continuation uses original agent", level: "unit", priority: "P0" },
    { id: "OC-FB-004", description: "Continuation uses correct model/variant", level: "unit", priority: "P0" },
    { id: "OC-FB-005", description: "Manual model overrides auto-captured", level: "integration", priority: "P0" },
    { id: "OC-FB-006", description: "Retryable provider error → next model", level: "unit", priority: "P0" },
    { id: "OC-FB-007", description: "Non-retryable error does not continue", level: "unit", priority: "P0" },
    { id: "OC-FB-008", description: "MessageAbortedError does not continue", level: "unit", priority: "P0" },
    { id: "OC-FB-009", description: "Tool finish idle then late EmptyOutputError → one continue", level: "unit", priority: "P0" },
    { id: "OC-FB-010", description: "Error first, idle later → one continue", level: "unit", priority: "P0" },
    { id: "OC-FB-011", description: "Duplicate error does not double-continue", level: "unit", priority: "P0" },
    { id: "OC-FB-012", description: "Duplicate idle does not double-continue", level: "unit", priority: "P0" },
    { id: "OC-FB-013", description: "Continuation failure not infinite loop", level: "unit", priority: "P0" },
    { id: "OC-FB-014", description: "After continuation, lease settled correctly", level: "unit", priority: "P0" },
    { id: "OC-FB-015", description: "Tool-call-as-text generates recovery prompt", level: "unit", priority: "P0" },
    { id: "OC-FB-016", description: "Normal code text not mistaken for tool call", level: "unit", priority: "P0" },
    { id: "OC-FB-017", description: "Continuation nonce not treated as human message", level: "unit", priority: "P0" },
    { id: "OC-FB-018", description: "New human message invalidates old continuation", level: "unit", priority: "P0" },
    { id: "OC-FB-019", description: "Session abort + fallback dispatch race safe", level: "unit", priority: "P0" },
    { id: "OC-FB-020", description: "Session delete cleans fallback runtime", level: "unit", priority: "P0" },
    { id: "OC-FB-021", description: "Crash after dispatch, before settle: no double-inject", level: "not-covered", priority: "P0" },
    { id: "OC-FB-022", description: "Crash after append, before dispatch: effect continues", level: "unit", priority: "P0" },
    { id: "OC-FB-023", description: "Different sessions generation/ordinal/lease isolated", level: "unit", priority: "P0" },
    { id: "OC-FB-024", description: "Fallback chain exhausted = final error, not silence", level: "unit", priority: "P0" },
  ],
  contextBudget: [
    { id: "OC-CB-001", description: "Provider input limit from /provider", level: "not-covered", priority: "P0", note: "demoted from real-e2e: no matching spec/test yet" },
    { id: "OC-CB-002", description: "Session model/provider from session API", level: "not-covered", priority: "P0", note: "demoted from real-e2e: no matching spec/test yet" },
    { id: "OC-CB-003", description: "Usage from real session token data", level: "not-covered", priority: "P0", note: "demoted from real-e2e: no matching spec/test yet" },
    { id: "OC-CB-004", description: "Below threshold = no budget nudge", level: "not-covered", priority: "P0", note: "demoted from real-e2e: no matching spec/test yet" },
    { id: "OC-CB-005", description: "Above threshold = one nudge injected", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-advanced.js", priority: "P0", test: "OC-CB-005 context budget nudge appears after threshold" },
    { id: "OC-CB-006", description: "Same phase no repeat nudge", level: "unit", priority: "P0" },
    { id: "OC-CB-007", description: "Backlog commit resets phase baseline", level: "not-covered", priority: "P0" },
    { id: "OC-CB-008", description: "After phase reset, condition met → nudge again", level: "not-covered", priority: "P0" },
    { id: "OC-CB-009", description: "Different sessions budget independent", level: "not-covered", priority: "P0" },
    { id: "OC-CB-010", description: "Provider missing limit = explicit fallback", level: "unit", priority: "P0" },
    { id: "OC-CB-011", description: "Missing usage does not fabricate value", level: "unit", priority: "P0" },
    { id: "OC-CB-012", description: "Session model switch re-resolves limit", level: "not-covered", priority: "P0" },
  ],
  compaction: [
    { id: "OC-COMP-001", description: "Real trigger of experimental.session.compacting", level: "not-covered", priority: "P0" },
    { id: "OC-COMP-002", description: "Output context includes backlog projection", level: "not-covered", priority: "P0" },
    { id: "OC-COMP-003", description: "compaction_started structured event", level: "not-covered", priority: "P0" },
    { id: "OC-COMP-004", description: "Compaction success = settled/compacted events", level: "not-covered", priority: "P0" },
    { id: "OC-COMP-005", description: "Autocontinue hook fires after compaction", level: "not-covered", priority: "P0" },
    { id: "OC-COMP-006", description: "Compaction continuation not a human turn", level: "not-covered", priority: "P0" },
    { id: "OC-COMP-007", description: "Compaction failure = failed settle event", level: "not-covered", priority: "P0" },
    { id: "OC-COMP-008", description: "Compaction failure cleans active owner", level: "not-covered", priority: "P0" },
    { id: "OC-COMP-009", description: "Late events for old compaction do not affect new", level: "not-covered", priority: "P0" },
    { id: "OC-COMP-010", description: "Restart recovers incomplete compaction", level: "not-covered", priority: "P0" },
    { id: "OC-COMP-011", description: "Two simultaneous compactions isolated", level: "not-covered", priority: "P0" },
    { id: "OC-COMP-012", description: "After summary, old tool output not re-injected", level: "not-covered", priority: "P0" },
  ],
  eventSourcing: [
    { id: "OC-ES-001", description: "First append creates NDJSON", level: "not-covered", priority: "P0" },
    { id: "OC-ES-002", description: "Multiple events each valid line", level: "not-covered", priority: "P0" },
    { id: "OC-ES-003", description: "Concurrent append no loss/interleaving", level: "not-covered", priority: "P0" },
    { id: "OC-ES-004", description: "Truncated last line handled on restart", level: "not-covered", priority: "P0" },
    { id: "OC-ES-005", description: "Corrupt mid-file line skipped or failed", level: "not-covered", priority: "P0" },
    { id: "OC-ES-006", description: "Replay projection == runtime projection", level: "not-covered", priority: "P0" },
    { id: "OC-ES-007", description: "Restart recovers review state", level: "not-covered", priority: "P0" },
    { id: "OC-ES-008", description: "Restart recovers backlog state", level: "not-covered", priority: "P0" },
    { id: "OC-ES-009", description: "Restart recovers nudge dedup state", level: "not-covered", priority: "P0" },
    { id: "OC-ES-010", description: "Restart recovers fallback lease state", level: "not-covered", priority: "P0" },
    { id: "OC-ES-011", description: "Restart recovers context phase state", level: "not-covered", priority: "P0" },
    { id: "OC-ES-012", description: "Session A events not folded into session B", level: "not-covered", priority: "P0" },
    { id: "OC-ES-013", description: "Append failure: memory does not exceed durable", level: "not-covered", priority: "P0" },
    { id: "OC-ES-014", description: "Orphan lock file recoverable", level: "not-covered", priority: "P0" },
    { id: "OC-ES-015", description: "kill -9 preserves up to last complete newline", level: "not-covered", priority: "P0" },
  ],
  lifecycle: [
    { id: "OC-LIFE-001", description: "New human message = human-turn fact", level: "unit", priority: "P0" },
    { id: "OC-LIFE-002", description: "Internal nudge not a human turn", level: "unit", priority: "P0" },
    { id: "OC-LIFE-003", description: "Child nonce message not a human turn", level: "unit", priority: "P0" },
    { id: "OC-LIFE-004", description: "Normal round: running/busy → terminal idle", level: "not-covered", priority: "P0" },
    { id: "OC-LIFE-005", description: "API error round: error → idle", level: "not-covered", priority: "P0" },
    { id: "OC-LIFE-006", description: "Abort = MessageAbortedError or equivalent", level: "not-covered", priority: "P0" },
    { id: "OC-LIFE-007", description: "Abort prevents pending tool execution", level: "not-covered", priority: "P0" },
    { id: "OC-LIFE-008", description: "Tool completed before abort not erased", level: "not-covered", priority: "P0" },
    { id: "OC-LIFE-009", description: "Abort + [DONE] race ≤ 1 terminal state", level: "unit", priority: "P0" },
    { id: "OC-LIFE-010", description: "Repeated idle idempotent", level: "unit", priority: "P0" },
    { id: "OC-LIFE-011", description: "session.deleted cleans PTY, fallback, compliance, queue, temp, actor", level: "not-covered", priority: "P0" },
    { id: "OC-LIFE-012", description: "Delete session A does not affect session B", level: "not-covered", priority: "P0" },
    { id: "OC-LIFE-013", description: "Event hook async work observable, no fixed sleep", level: "not-covered", priority: "P0" },
    { id: "OC-LIFE-014", description: "session.post and event two paths do not double-recover", level: "unit", priority: "P0" },
    { id: "OC-LIFE-015", description: "User sends next prompt immediately after idle, no race", level: "not-covered", priority: "P0" },
  ],
  concurrency: [
    { id: "OC-CONC-001", description: "10 sessions on same host, no cross-talk", level: "not-covered", priority: "P0" },
    { id: "OC-CONC-002", description: "Two sessions write without polluting runtime", level: "not-covered", priority: "P0" },
    { id: "OC-CONC-003", description: "Two sessions nudge = each sends once", level: "not-covered", priority: "P0" },
    { id: "OC-CONC-004", description: "Two sessions fallback = independent continuation IDs", level: "not-covered", priority: "P0" },
    { id: "OC-CONC-005", description: "Two sessions child sessions = correct ownership", level: "not-covered", priority: "P0" },
    { id: "OC-CONC-006", description: "Same session multi-tool-call ordering", level: "not-covered", priority: "P0" },
    { id: "OC-CONC-007", description: "Out-of-order event injection → consistent fold", level: "unit", priority: "P0" },
    { id: "OC-CONC-008", description: "High-frequency idle/error no unbounded queue", level: "unit", priority: "P0" },
    { id: "OC-CONC-009", description: "100 rounds, runtime store does not keep ended session data", level: "not-covered", priority: "P0" },
    { id: "OC-CONC-010", description: "Repeated create/delete = no PTY/actor/iterator/lock leak", level: "not-covered", priority: "P0" },
    { id: "OC-CONC-011", description: "Mock provider delay, other sessions still run", level: "not-covered", priority: "P0" },
    { id: "OC-CONC-012", description: "Restart frees old port, SSE, provider socket", level: "not-covered", priority: "P0" },
  ],
  stability: [
    { id: "OC-STAB-001", description: "Stability gate runner repeat-e2e-50 execution", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-gate.js", priority: "P0", test: "OC-STAB-001 stability gate repeat execution" },
    { id: "OC-STAB-002", description: "Static gate validation for sleep and containsTool", level: "real-e2e", spec: "e2e/opencode/specs/p0-canary-tests-gate.js", priority: "P0", test: "OC-STAB-002 static gate validation" }
  ],
};
