module Wanxiangshu.Methodology.Catalog1

open Wanxiangshu.Methodology.SchemaCommon

let schemas: MethodologySchema list = [
    buildSchema
        "first_principles"
        "Reduce the problem to irreducible facts and rebuild from them."
        "When inherited assumptions, frameworks, or copy-paste patterns obscure what must be true."
        [ reqStr "problem_statement" "One paragraph stating the deliverable, success signal, and what is explicitly out of scope for this reasoning pass."
          reqArr "assumptions_to_strip" 2 "List assumptions you are temporarily suspending (organizational, framework, prior design). Each item names the assumption and why it might be accidental complexity."
          reqArr "atomic_facts" 3 "Facts that remain after stripping: observables, file paths, test outcomes, protocol guarantees, or user-stated requirements. No interpretation yet."
          reqArr "rebuild_steps" 3 "Ordered steps to reconstruct a solution only from atomic facts. Each step should add one justified layer (model, interface, algorithm, test)."
          reqStr "irreducible_core" "The smallest description of the problem that still captures all constraints; should be short enough to fit in a README section."
          reqArr "rejected_shortcuts" 1 "Shortcuts or patterns you refuse to use until first-principles rebuild completes, with one-line justification each."
          optArr "open_questions" 1 "Questions that block rebuild; each should name what evidence would answer it."
          optStr "workspace_anchors" "Comma-separated paths, modules, or symbols this rebuild must respect or replace." ]
        "Strip inherited narratives until only workspace-anchored facts remain, then rebuild a minimal architecture story."
        [ "Stripped assumption ledger"
          "Atomic fact table"
          "Rebuild chain"
          "Irreducible core statement"
          "Rejected shortcuts and why"
          "Next executable actions for the parent agent" ]
    buildSchema
        "axiomatization"
        "State primitive terms, allowed operations, invariants, forbidden states, and derivation rules explicitly; then solve only inside that declared system."
        "When definitions drift, hidden assumptions make reasoning unstable, or multiple teams talk past each other."
        [ reqStr "system_name" "Short name for the formal slice you are axiomatizing (e.g. review loop, todo projection, tool permission)."
          reqArr "primitive_terms" 3 "Undefined carriers of meaning in this slice. Each entry: term + one-sentence intended meaning in this repo."
          reqArr "allowed_operations" 2 "Operations agents or code may perform on those terms. Include preconditions in the same bullet."
          reqArr "invariants" 3 "Properties that must hold in every legal state (ordering, uniqueness, idempotency, conservation)."
          reqArr "forbidden_states" 2 "Explicit illegal combinations (e.g. two in_progress todos, review active without task id)."
          reqArr "derivation_rules" 2 "If A and B then C style rules grounded in files or tests; cite path when possible."
          reqStr "scope_boundary" "What this axiom system intentionally does not cover."
          optArr "consistency_checks" 1 "Executable checks (tests, grep, architecture gates) that would falsify the axiom set."
          optStr "known_ambiguities" "Terms still contested; propose disambiguation before coding." ]
        "Freeze vocabulary and legal moves so downstream edits cannot smuggle undefined behavior."
        [ "Primitive term glossary"
          "Operation table with preconditions"
          "Invariant list"
          "Forbidden states"
          "Derivation rules applied to current task"
          "Consistency checks"
          "Next actions" ]
    buildSchema
        "deduction"
        "Derive necessary conclusions from accepted premises."
        "When premises are already agreed (tests, types, docs, user rules) and you need forced implications."
        [ reqArr "accepted_premises" 2 "Premises everyone must accept this turn: cite source (test name, file, user message, invariant)."
          reqStr "target_claim" "The conclusion you need to establish or refute."
          reqArr "inference_steps" 2 "Each step: from which premises, which rule of inference, which intermediate conclusion. No skipped leaps."
          reqStr "final_conclusion" "The deduced statement in declarative form."
          reqArr "premises_not_used" 1 "Relevant premises you explicitly did not need (documents scope discipline)."
          optArr "counterarguments" 1 "Lines of attack against the deduction; show why they fail given accepted premises."
          optStr "formalization_sketch" "Optional propositional or type-level sketch if it clarifies the chain."
          optArr "testable_corollaries" 1 "Corollaries that should become tests or grep gates." ]
        "Chain truth-preserving steps from agreed premises to a conclusion the parent can act on."
        [ "Premise ledger"
          "Inference chain"
          "Final conclusion"
          "Unused premises"
          "Corollaries and tests"
          "Next actions" ]
    buildSchema
        "induction"
        "Infer a general rule from repeated cases or patterns."
        "When you have multiple concrete instances and need a guarded generalization for the codebase."
        [ reqArr "observed_cases" 3 "Concrete cases: file paths, test names, log lines, or user examples. One case per bullet."
          reqStr "shared_pattern" "What repeats across cases (structure, failure mode, naming, data shape)."
          reqStr "proposed_rule" "General rule in if-when-then form scoped to this project."
          reqArr "supporting_evidence" 2 "Why each case supports the rule; note weight of each case."
          reqArr "exceptions_seen" 1 "Cases that almost fit but differ; explain whether they falsify or narrow the rule."
          reqStr "confidence_bounds" "What would increase or decrease confidence (more tests, counterexample, wider sample)."
          optArr "predictions" 2 "New situations where the rule should hold; parent can verify."
          optStr "anti_pattern" "What developers should stop doing if the rule is adopted." ]
        "Generalize from repeated workspace evidence without overclaiming beyond the sample."
        [ "Case table"
          "Pattern statement"
          "Proposed rule"
          "Exception handling"
          "Predictions to verify"
          "Next actions" ]
    buildSchema
        "abduction"
        "Generate the best causal hypothesis for surprising evidence, then seek discriminating tests."
        "When debugging, diagnosing, investigating, or explaining outcomes that violate expectations."
        [ reqStr "surprising_evidence" "What was observed that conflicted with expectation; include exact error strings or metrics if any."
          reqStr "context_anchor" "Where in the repo, session, or runtime this appeared (paths, commands, hook names)."
          reqStr "hypothesis" "Best causal explanation: if X then we would see Y. One primary hypothesis."
          reqArr "discriminating_tests" 2 "Tests or reads that distinguish this hypothesis from alternatives; must be executable by parent."
          reqArr "alternative_hypotheses" 1 "Other plausible causes ranked weaker; one line each."
          reqStr "expected_observations_if_true" "What else should be true if the primary hypothesis holds."
          optArr "ruled_out_paths" 1 "Investigations already done that eliminated simpler causes."
          optStr "stop_rule" "When to abandon this hypothesis (what counterevidence would suffice)." ]
        "Propose the best explanation for surprise and spell discriminating checks—not treat guess as fact."
        [ "Evidence summary"
          "Primary hypothesis"
          "Alternatives"
          "Discriminating test plan"
          "Expected observations"
          "Next actions" ]
    buildSchema
        "analogy"
        "Transfer a known solution structure from a genuinely similar problem."
        "When a canonical template elsewhere in the repo or domain likely shares topology with the current task."
        [ reqStr "source_domain" "The known problem or module you are analogizing from (path or product name)."
          reqStr "target_domain" "The current problem location in this workspace."
          reqArr "shared_structure" 3 "Mappings: source facet → target facet (roles, data flow, state machine shape)."
          reqArr "transferred_tactics" 2 "Concrete tactics to copy (file layout, hook order, test pattern) with edits noted."
          reqArr "mismatch_risks" 2 "Where the analogy breaks (different host, sync vs async, permission model)."
          reqStr "similarity_argument" "Why similarity is structural not superficial keyword match."
          optArr "anti_analogies" 1 "Similar-looking cases that must not be copied; explain difference."
          optStr "adaptation_checklist" "Ordered edits to apply the analogy safely here." ]
        "Map structure from a proven neighbor problem and stress-test mismatches before copying code."
        [ "Source–target mapping"
          "Transferred tactics"
          "Mismatch risks"
          "Adaptation checklist"
          "Next actions" ]
    buildSchema
        "specialization"
        "Inspect simple, concrete, boundary, or extreme cases before generalizing."
        "Before designing a general API, algorithm, or refactor covering many inputs."
        [ reqStr "general_problem" "The broad problem you might over-engineer if you skip concrete cases."
          reqArr "concrete_instances" 3 "Specific inputs: smallest file, empty workspace, single-tool session, max enum size, etc."
          reqArr "boundary_cases" 2 "Edges: null, empty list, duplicate keys, restart mid-review, very short background."
          reqArr "extreme_cases" 1 "Stress cases: 54 tools registered, huge message history, concurrent hooks."
          reqStr "lessons_per_instance" "What each instance teaches about necessary vs accidental structure."
          optArr "generalization_blockers" 1 "Facts learned only from one instance that block a naive general rule."
          optStr "minimal_general_form" "Smallest generalization that still covers listed instances." ]
        "Ground design in named concrete and boundary instances before writing generic code."
        [ "Instance catalog"
          "Boundary and extreme notes"
          "Per-instance lessons"
          "Minimal general form"
          "Next actions" ]
    buildSchema
        "generalization"
        "Widen the problem to expose the underlying structure."
        "When a local fix hides a missing abstraction or repeated pattern across modules."
        [ reqStr "local_symptom" "The narrow bug or request that triggered the turn."
          reqStr "widened_view" "The larger class of problems this symptom belongs to (cross-host, all tools, all sessions)."
          reqArr "structural_invariants" 2 "What stays true when you widen (kernel purity, event history as truth)."
          reqArr "variation_dimensions" 2 "Axes along which instances differ (Mux vs Opencode, sync vs async)."
          reqStr "proposed_abstraction" "The abstraction that captures the widened view (module, type, pipeline stage)."
          reqArr "instances_covered" 2 "Concrete places the abstraction must cover; cite paths."
          optArr "instances_excluded" 1 "Where widening would be wrong; keep scope honest."
          optStr "refactor_slice" "Smallest slice to validate the abstraction before full rollout." ]
        "Lift from local patch to structural abstraction with explicit coverage and exclusions."
        [ "Widened problem statement"
          "Abstraction proposal"
          "Coverage map"
          "Excluded cases"
          "Next actions" ]
    buildSchema
        "working_backwards"
        "Start from the desired end state and derive prerequisites."
        "When the goal is clear but the path is muddy; integration tests or UX outcomes are known."
        [ reqStr "desired_end_state" "Observable done: test green, tool registered, user-visible behavior, merge criteria."
          reqArr "acceptance_signals" 2 "Binary checks that prove the end state (command, assertion, screenshot description)."
          reqArr "prerequisite_chain" 3 "Backward chain: last step before done, then its prerequisites, down to today."
          reqStr "current_position" "Where the workspace is now relative to the chain."
          reqArr "blocking_gaps" 1 "Missing artifacts, unknown APIs, or unmerged branches on the critical path."
          optArr "parallel_tracks" 1 "Work that can proceed without blocking the main chain."
          optStr "first_forward_step" "The single next forward action that moves from current_position." ]
        "Reverse-plan from acceptance signals to today's executable first step."
        [ "End state definition"
          "Prerequisite chain"
          "Gap analysis"
          "First forward step"
          "Next actions" ]
    buildSchema
        "analysis_synthesis"
        "Analyze backward from the desired result to known facts, then synthesize forward into a plan."
        "When the goal is clear but construction path is not; large features or refactors."
        [ reqStr "target_result" "What must exist at the end (behavior, files, tests)."
          reqArr "backward_analysis" 3 "Working backward: each bullet states a required condition and whether it is already true in repo."
          reqArr "known_facts" 2 "Anchored facts from code, tests, docs—no speculation."
          reqArr "synthesis_steps" 3 "Forward build order: each step produces an artifact the next step needs."
          reqStr "integration_point" "Where synthesized pieces plug into existing Kernel/Shell/Opencode/Mux boundaries."
          optArr "risks_in_synthesis" 1 "Ordering risks, double work, or host divergence."
          optStr "validation_milestone" "Mid-point check before full synthesis completes." ]
        "Split backward feasibility analysis from forward construction schedule."
        [ "Backward condition table"
          "Known facts"
          "Forward synthesis plan"
          "Integration point"
          "Next actions" ]
    buildSchema
        "auxiliary_construction"
        "Introduce a helper representation that exposes a hidden relation between known and unknown."
        "When direct attack fails and a lemma, adapter, IR, or invariant would bridge facts to target."
        [ reqStr "known_side" "What is already established in code or specs."
          reqStr "unknown_target" "What you cannot reach directly yet."
          reqStr "auxiliary_object" "The helper you introduce: type, function, file, test harness, YAML template."
          reqStr "exposed_relation" "What hidden link the auxiliary makes visible."
          reqArr "construction_steps" 2 "How to build the auxiliary minimally in this repo."
          reqArr "discharge_steps" 2 "How to eliminate the auxiliary later or prove the target via it."
          optStr "placement" "Kernel vs Shell vs Methodology vs host adapter for the auxiliary."
          optArr "failure_modes" 1 "Ways the auxiliary could become permanent accidental complexity." ]
        "Design a minimal bridge object and plan to discharge it after the target is reachable."
        [ "Known vs unknown"
          "Auxiliary design"
          "Construction and discharge"
          "Placement recommendation"
          "Next actions" ]
    buildSchema
        "equivalent_transformation"
        "Convert the problem into an equivalent form where reasoning or implementation is easier."
        "When the current representation is noisy: control flow, JSON blobs, implicit state."
        [ reqStr "source_representation" "How the problem is stated today (code shape, protocol, message flow)."
          reqStr "target_representation" "Equivalent form: events, graph, types, algebra, tables."
          reqStr "equivalence_claim" "Why solutions in target map 1:1 to source (preserved observables)."
          reqArr "transformation_steps" 2 "Mechanical rewrite steps safe for this codebase."
          reqArr "preserved_properties" 2 "Invariants that must survive the transform (ordering, idempotency, permissions)."
          optArr "lost_detail" 1 "Information dropped in transform and how to recover if needed."
          optStr "verification" "Test or diff strategy proving equivalence." ]
        "Justify a representation change and list preserved observables before rewriting."
        [ "Source vs target representation"
          "Equivalence argument"
          "Transformation steps"
          "Verification plan"
          "Next actions" ]
    buildSchema
        "decomposition_recombination"
        "Split the object into parts and reconnect them in a better structure."
        "When a module, tool surface, or workflow is too entangled to edit safely."
        [ reqStr "whole_artifact" "The system or file cluster being split (paths)."
          reqArr "parts" 3 "Named parts with single responsibility each."
          reqArr "interfaces_between_parts" 2 "Contracts between parts: types, events, pure functions, no hidden globals."
          reqStr "recombined_shape" "How parts should be wired after split (dependency direction)."
          reqArr "migration_slices" 2 "Order of moves that keep build green between steps."
          optArr "coupling_to_cut" 1 "Forbidden imports or shared mutable state to eliminate."
          optStr "architecture_test_hooks" "Existing or new gates that enforce the new seams." ]
        "Propose a part graph and migration slices that respect vibe-fs layering."
        [ "Decomposition map"
          "Interface contracts"
          "Recombined architecture"
          "Migration slices"
          "Next actions" ]
]
