module Wanxiangshu.Methodology.Catalog1

open Wanxiangshu.Methodology.SchemaCommon

let entries: MethodologyEntry list = [
    { methodologyId = "first_principles"
      shortDefinition = "Reduce the problem to irreducible facts and rebuild from them."
      triggerWhen = "When inherited assumptions, frameworks, or copy-paste patterns obscure what must be true."
      noteDescription = "problem_statement, assumptions_to_strip, atomic_facts, rebuild_steps, irreducible_core, discarded_shortcuts, open_questions, workspace_anchors"
      meditatorRole = "Strip inherited narratives until only workspace-anchored facts remain, then rebuild a minimal architecture story."
      outputSections = [ "Stripped assumption ledger"; "Atomic fact table"; "Rebuild chain"; "Irreducible core statement"; "Discarded shortcuts and why"; "Next executable actions for the parent agent" ] }
    { methodologyId = "axiomatization"
      shortDefinition = "State primitive terms, allowed operations, invariants, forbidden states, and derivation rules explicitly; then solve only inside that declared system."
      triggerWhen = "When definitions drift, hidden assumptions make reasoning unstable, or multiple teams talk past each other."
      noteDescription = "system_name, primitive_terms, allowed_operations, invariants, forbidden_states, derivation_rules, scope_boundary, consistency_checks, known_ambiguities"
      meditatorRole = "Freeze vocabulary and legal moves so downstream edits cannot smuggle undefined behavior."
      outputSections = [ "Primitive term glossary"; "Operation table with preconditions"; "Invariant list"; "Forbidden states"; "Derivation rules applied to current task"; "Consistency checks"; "Next actions" ] }
    { methodologyId = "deduction"
      shortDefinition = "Derive necessary conclusions from accepted premises."
      triggerWhen = "When premises are already agreed (tests, types, docs, user rules) and you need forced implications."
      noteDescription = "accepted_premises, target_claim, inference_steps, final_conclusion, premises_not_used, counterarguments, formalization_sketch, testable_corollaries"
      meditatorRole = "Chain truth-preserving steps from agreed premises to a conclusion the parent can act on."
      outputSections = [ "Premise ledger"; "Inference chain"; "Final conclusion"; "Unused premises"; "Corollaries and tests"; "Next actions" ] }
    { methodologyId = "induction"
      shortDefinition = "Infer a general rule from repeated cases or patterns."
      triggerWhen = "When you have multiple concrete instances and need a guarded generalization for the codebase."
      noteDescription = "observed_cases, shared_pattern, proposed_rule, supporting_evidence, exceptions_seen, confidence_bounds, predictions, anti_pattern"
      meditatorRole = "Generalize from repeated workspace evidence without overclaiming beyond the sample."
      outputSections = [ "Case table"; "Pattern statement"; "Proposed rule"; "Exception handling"; "Predictions to verify"; "Next actions" ] }
    { methodologyId = "abduction"
      shortDefinition = "Generate the best causal hypothesis for surprising evidence, then seek discriminating tests."
      triggerWhen = "When debugging, diagnosing, investigating, or explaining outcomes that violate expectations."
      noteDescription = "surprising_evidence, context_anchor, hypothesis, discriminating_tests, alternative_hypotheses, expected_observations_if_true, ruled_out_paths, stop_rule"
      meditatorRole = "Propose the best explanation for surprise and spell discriminating checks—not treat guess as fact."
      outputSections = [ "Evidence summary"; "Primary hypothesis"; "Alternatives"; "Discriminating test plan"; "Expected observations"; "Next actions" ] }
    { methodologyId = "analogy"
      shortDefinition = "Transfer a known solution structure from a genuinely similar problem."
      triggerWhen = "When a canonical template elsewhere in the repo or domain likely shares topology with the current task."
      noteDescription = "source_domain, target_domain, shared_structure, transferred_tactics, mismatch_risks, similarity_argument, anti_analogies, adaptation_checklist"
      meditatorRole = "Map structure from a proven neighbor problem and stress-test mismatches before copying code."
      outputSections = [ "Source–target mapping"; "Transferred tactics"; "Mismatch risks"; "Adaptation checklist"; "Next actions" ] }
    { methodologyId = "specialization"
      shortDefinition = "Inspect simple, concrete, boundary, or extreme cases before generalizing."
      triggerWhen = "Before designing a general API, algorithm, or refactor covering many inputs."
      noteDescription = "general_problem, concrete_instances, boundary_cases, extreme_cases, lessons_per_instance, generalization_blockers, minimal_general_form"
      meditatorRole = "Ground design in named concrete and boundary instances before writing generic code."
      outputSections = [ "Instance catalog"; "Boundary and extreme notes"; "Per-instance lessons"; "Minimal general form"; "Next actions" ] }
    { methodologyId = "generalization"
      shortDefinition = "Widen the problem to expose the underlying structure."
      triggerWhen = "When a local fix hides a missing abstraction or repeated pattern across modules."
      noteDescription = "local_symptom, widened_view, structural_invariants, variation_dimensions, proposed_abstraction, instances_covered, instances_excluded, refactor_slice"
      meditatorRole = "Lift from local patch to structural abstraction with explicit coverage and exclusions."
      outputSections = [ "Widened problem statement"; "Abstraction proposal"; "Coverage map"; "Excluded cases"; "Next actions" ] }
    { methodologyId = "working_backwards"
      shortDefinition = "Start from the desired end state and derive prerequisites."
      triggerWhen = "When the goal is clear but the path is muddy; integration tests or UX outcomes are known."
      noteDescription = "desired_end_state, acceptance_signals, prerequisite_chain, current_position, blocking_gaps, parallel_tracks, first_forward_step"
      meditatorRole = "Reverse-plan from acceptance signals to today's executable first step."
      outputSections = [ "End state definition"; "Prerequisite chain"; "Gap analysis"; "First forward step"; "Next actions" ] }
    { methodologyId = "analysis_synthesis"
      shortDefinition = "Analyze backward from the desired result to known facts, then synthesize forward into a plan."
      triggerWhen = "When the goal is clear but construction path is not; large features or refactors."
      noteDescription = "target_result, backward_analysis, known_facts, synthesis_steps, integration_point, risks_in_synthesis, validation_milestone"
      meditatorRole = "Split backward feasibility analysis from forward construction schedule."
      outputSections = [ "Backward condition table"; "Known facts"; "Forward synthesis plan"; "Integration point"; "Next actions" ] }
    { methodologyId = "auxiliary_construction"
      shortDefinition = "Introduce a helper representation that exposes a hidden relation between known and unknown."
      triggerWhen = "When direct attack fails and a lemma, adapter, IR, or invariant would bridge facts to target."
      noteDescription = "known_side, unknown_target, auxiliary_object, exposed_relation, construction_steps, discharge_steps, placement, failure_modes"
      meditatorRole = "Design a minimal bridge object and plan to discharge it after the target is reachable."
      outputSections = [ "Known vs unknown"; "Auxiliary design"; "Construction and discharge"; "Placement recommendation"; "Next actions" ] }
    { methodologyId = "equivalent_transformation"
      shortDefinition = "Convert the problem into an equivalent form where reasoning or implementation is easier."
      triggerWhen = "When the current representation is noisy: control flow, JSON blobs, implicit state."
      noteDescription = "source_representation, target_representation, equivalence_claim, transformation_steps, preserved_properties, lost_detail, verification"
      meditatorRole = "Justify a representation change and list preserved observables before rewriting."
      outputSections = [ "Source vs target representation"; "Equivalence argument"; "Transformation steps"; "Verification plan"; "Next actions" ] }
    { methodologyId = "decomposition_recombination"
      shortDefinition = "Split the object into parts and reconnect them in a better structure."
      triggerWhen = "When a module, tool surface, or workflow is too entangled to edit safely."
      noteDescription = "whole_artifact, parts, interfaces_between_parts, recombined_shape, migration_slices, coupling_to_cut, architecture_test_hooks"
      meditatorRole = "Propose a part graph and migration slices that respect vibe-fs layering."
      outputSections = [ "Decomposition map"; "Interface contracts"; "Recombined architecture"; "Migration slices"; "Next actions" ] }
]
