module Wanxiangshu.Methodology.Catalog3

open Wanxiangshu.Methodology.SchemaCommon

let schemas: MethodologySchema list = [
    buildSchema
        "dynamic_programming"
        "Exploit overlapping subproblems and optimal substructure with memoized state transitions."
        "When repeated subtasks appear (schema gen per tool, replay segments, fuzzy pages)."
        [ reqStr "top_level_goal" "End computation or design you need."
          reqArr "subproblems" 3 "Reusable subtasks with clear inputs/outputs."
          reqArr "overlap_evidence" 2 "Where the same subproblem appears multiple times in this work."
          reqStr "state_definition" "DP state keys (session id, iterator, tool name)."
          reqArr "transitions" 2 "How to combine sub-solutions."
          reqStr "memoization_plan" "Where to cache (Shell store, pure Map, file cache) and invalidation."
          optArr "base_cases" 2 "Terminal subproblems with known answers."
          optStr "complexity_note" "Time/space vs naive recursion." ]
        "Factor overlapping work into memoized states appropriate for vibe-fs stores."
        [ "Subproblem decomposition"
          "State and transitions"
          "Memoization"
          "Next actions" ]
    buildSchema
        "monte_carlo_sampling"
        "Sample plausible paths when space is too large; verify critical findings deterministically."
        "When exhaustive reasoning over sessions, tool combos, or message orderings is infeasible."
        [ reqStr "decision_question" "What you need approximate confidence about."
          reqArr "sample_space" 2 "What varies across samples (tool args, hook order, random seeds)."
          reqArr "samples_drawn" 3 "Concrete samples you will or did try (commands, scenarios)."
          reqStr "stability_signal" "Pattern that stayed stable across samples."
          reqArr "deterministic_followups" 2 "Must-verify checks after sampling (specific test, grep gate)."
          optStr "sample_size_rationale" "Why this many samples is enough for this risk level."
          optArr "outliers" 1 "Samples that broke the pattern." ]
        "Sample cheaply then nail truth with deterministic verification."
        [ "Sampling plan"
          "Stable signal"
          "Outliers"
          "Deterministic followups"
          "Next actions" ]
    buildSchema
        "simulated_annealing"
        "Accept worse interim states early to escape local optima; cool into refinement."
        "When greedy refactor or fix order gets stuck in a local minimum."
        [ reqStr "objective_function" "What you are improving (test pass rate, architecture gate count, latency)."
          reqStr "current_state" "Stuck local optimum description."
          reqArr "neighbor_moves" 3 "Small mutations that might worsen short-term score."
          reqStr "acceptance_policy" "When to accept worse moves (exploration phase rules)."
          reqStr "cooling_schedule" "How exploration narrows into refinement this session."
          optArr "best_so_far" 1 "Best state encountered."
          optStr "termination" "When to stop annealing and commit." ]
        "Plan exploration vs exploitation when incremental edits plateau."
        [ "Objective"
          "Neighbor moves"
          "Annealing schedule"
          "Commit criteria"
          "Next actions" ]
    buildSchema
        "swarm_optimization"
        "Parallel candidate directions explore, share best findings, converge without early overcommit."
        "When multiple subagents, hypotheses, or design drafts can search in parallel."
        [ reqStr "collective_goal" "What the swarm optimizes (find root cause, design schema set)."
          reqArr "agents_or_hypotheses" 3 "Parallel tracks: coder intents, investigator questions, design options."
          reqStr "share_mechanism" "How findings merge (todo report, KG, parent synthesis)."
          reqArr "diversity_rules" 2 "How to keep agents from duplicating the same search."
          reqArr "convergence_criteria" 2 "When to stop spawning and pick a winner."
          optStr "best_candidate" "Current leader and evidence."
          optArr "retired_candidates" 1 "Tracks killed and why." ]
        "Orchestrate parallel exploration with explicit merge and convergence rules."
        [ "Swarm layout"
          "Sharing protocol"
          "Convergence"
          "Leader candidate"
          "Next actions" ]
    buildSchema
        "systems_thinking"
        "Model feedback loops, dependencies, delays, and emergent behavior."
        "When a change in hooks, tools, or prompts ripples through sessions and review loops."
        [ reqStr "system_boundary" "What is inside the diagram (plugin, session, KG job, review FSM)."
          reqArr "stocks" 2 "Accumulations: message history, todo backlog, mutable maps."
          reqArr "flows" 2 "Rates of change: tool execute, transform, background reviewer."
          reqArr "feedback_loops" 2 "Reinforcing or balancing loops (nudge → todowrite → probe suppress)."
          reqArr "delays" 1 "Where lag causes oscillation or stale state (async bookkeeper)."
          reqStr "emergent_risk" "Behavior not visible in a single module."
          optArr "leverage_points" 1 "High-impact intervention spots."
          optStr "simulation_or_trace" "How to walk one session through the loops." ]
        "Draw loops and delays so host-side tweaks are not judged in isolation."
        [ "Stock-flow sketch"
          "Feedback loops"
          "Delays"
          "Leverage points"
          "Next actions" ]
    buildSchema
        "root_cause_analysis"
        "Trace symptoms to causal fault, not visible failure only."
        "When repeated failures, flaky tests, or incident-like tool errors need depth."
        [ reqStr "symptom" "What users or tests see (message, count mismatch, timeout)."
          reqStr "visible_failure" "Immediate failing component (assertion line, hook)."
          reqArr "why_chain" 4 "Five-whys style chain: each why backed by evidence or marked hypothesis."
          reqStr "root_cause" "Actionable fault (wrong assumption, missing gate, race)."
          reqArr "contributing_factors" 1 "Factors that amplified but are not root."
          reqStr "fix_target" "What to change so symptom cannot recur."
          optArr "verification_after_fix" 2 "Tests or traces proving root addressed."
          optStr "symptom_vs_cause_guard" "How to avoid stopping at visible_failure." ]
        "Drive why-chain to an actionable root with verification, not patch-the-symptom."
        [ "Symptom vs visible failure"
          "Why chain"
          "Root cause"
          "Fix target"
          "Verification"
          "Next actions" ]
    buildSchema
        "state_machine_reasoning"
        "Enumerate legal states, transitions, and impossible states."
        "When behavior is modal: review, nudge, KG job, todo in_progress discipline."
        [ reqStr "machine_name" "Which FSM (ReviewSession, Nudge, MagicTodo projection)."
          reqArr "states" 3 "Named states with payload each carries."
          reqArr "transitions" 3 "Event-triggered edges; cite kernel module if known."
          reqArr "illegal_states" 2 "Combinations that must be unrepresentable or rejected."
          reqStr "current_state_guess" "Where this session or workspace is now."
          optArr "missing_transitions" 1 "Gaps between spec and implementation."
          optStr "exhaustiveness_check" "How compiler or tests enforce match exhaustiveness." ]
        "Make FSM explicit and align implementation with illegal state elimination."
        [ "State list"
          "Transition table"
          "Illegal states"
          "Gap analysis"
          "Next actions" ]
    buildSchema
        "type_driven_design"
        "Encode domain boundaries and illegal states in types."
        "Before implementing hooks or tools still passing Dyn obj through business logic."
        [ reqStr "domain_slice" "Boundary to type (methodology args, review verdict, tool permission)."
          reqArr "illegal_states_today" 2 "Bad combos currently representable (null task id, empty intents)."
          reqArr "algebraic_model" 3 "DU/records: cases, fields, smart constructors."
          reqStr "encoding_plan" "Where types live (Kernel) and where decode happens (Shell/codec)."
          reqArr "operations_as_functions" 2 "Pure functions on types replacing boolean flags."
          optArr "compiler_guarantees" 1 "What mistakes become compile errors."
          optStr "migration_from_dyn" "Steps to shrink Dyn surface." ]
        "Design types so illegal states are unwritable before coding handlers."
        [ "Illegal state inventory"
          "Algebraic model"
          "Codec boundary"
          "Migration steps"
          "Next actions" ]
    buildSchema
        "event_sourcing"
        "Separate commands from facts; derive current state from event history."
        "When mutable maps disagree with message history or replay is required."
        [ reqStr "command_side" "Intents that can be rejected (tool call, user message, submit_review)."
          reqStr "event_side" "Facts once accepted (tool result, verdict YAML, KG append)."
          reqArr "events_list" 2 "Event types in this slice with payload shape."
          reqStr "fold_function" "How events reduce to current projection."
          reqArr "replay_requirements" 2 "Ordering, idempotency, version fields."
          optStr "snapshot_policy" "When snapshots are bookmarks only vs truth."
          optArr "correction_events" 1 "Compensating events instead of UPDATE."
          optStr "anti_patterns" "In-place mutation destroying audit trail." ]
        "Align command/event split with history-as-truth discipline in vibe-fs."
        [ "Command vs event"
          "Event catalog"
          "Fold/replay"
          "Correction strategy"
          "Next actions" ]
    buildSchema
        "operationalism"
        "Define concepts by observable operations that detect or change them; discard non-behavioral distinctions."
        "When vague terms (done, stable, registered) need testable meaning."
        [ reqStr "vague_term" "Word or concept causing misalignment (parity, compatible, safe)."
          reqArr "observation_operations" 3 "Commands, tests, or grep gates that detect the concept."
          reqArr "mutation_operations" 2 "Operations that change the concept's presence."
          reqStr "equivalence_criterion" "Two implementations are the same iff observations match."
          reqArr "discarded_distinctions" 1 "Labels that make no observational difference."
          optStr "operational_spec" "Single paragraph spec engineers can implement."
          optArr "counterexamples" 1 "Cases where old vocabulary misled." ]
        "Replace metaphysical labels with observation/mutation specs."
        [ "Term under scrutiny"
          "Operational definition"
          "Discarded distinctions"
          "Implementable spec"
          "Next actions" ]
    buildSchema
        "bayesian_update"
        "Update belief strength as evidence arrives; avoid all-or-nothing after one test."
        "When multiple hypotheses compete (host bug vs kernel bug vs stale build)."
        [ reqStr "hypothesis_set" "Mutually exclusive or overlapping hypotheses with short labels."
          reqArr "prior_weights" 2 "Before new evidence: qualitative or numeric priors and why."
          reqArr "new_evidence" 2 "Fresh observations this turn."
          reqArr "likelihood_sketch" 2 "P(evidence|hypothesis) qualitative: which hypothesis each evidence favors."
          reqStr "posterior_summary" "Ranking after update; no false precision required."
          optArr "decisive_experiment" 1 "Next evidence that would swing posterior most."
          optStr "discarded_hypotheses" "Hypotheses effectively ruled out." ]
        "Qualitative Bayesian update over competing engineering hypotheses."
        [ "Priors"
          "Evidence"
          "Likelihood notes"
          "Posterior"
          "Decisive experiment"
          "Next actions" ]
    buildSchema
        "falsification"
        "Formulate hypotheses with clear failure conditions; search counterexamples."
        "When a design claim risks becoming unfalsifiable narrative."
        [ reqStr "claim" "Strong statement to stress-test (always works, never needs X)."
          reqArr "failure_conditions" 2 "What observation would refute the claim."
          reqArr "search_attempts" 3 "Counterexample hunts: tests, edge inputs, hostile sequences."
          reqStr "verdict" "Survives, refuted, or scoped narrower."
          reqArr "surviving_scope" 1 "Honest weaker claim if refuted."
          optStr "popper_note" "What would make the claim unfalsifiable and must be avoided."
          optArr "new_tests" 1 "Tests to encode surviving scope." ]
        "Try to kill the claim before shipping it."
        [ "Claim"
          "Failure conditions"
          "Search log"
          "Verdict and revised scope"
          "Next actions" ]
    buildSchema
        "thought_experiment"
        "Push idealized or extreme scenarios through rules to test concept boundaries."
        "When real execution is costly or dangerous (data loss, prod hook, oversized payloads)."
        [ reqStr "scenario_setup" "Idealized world assumptions (infinite history, zero latency, malicious LLM)."
          reqStr "rule_under_test" "Policy or code rule you are exercising mentally."
          reqArr "scenario_steps" 3 "Sequence of events in the thought experiment."
          reqStr "derived_outcome" "What happens if rules are applied consistently."
          reqArr "boundary_insights" 2 "Contradictions or edge cases revealed."
          optStr "mapping_to_real" "Which parts of scenario are realistic in vibe-fs."
          optArr "real_tests_inspired" 1 "Concrete tests inspired by the experiment." ]
        "Stress rules in imagination before paying execution cost."
        [ "Scenario"
          "Steps"
          "Outcome"
          "Insights"
          "Inspired tests"
          "Next actions" ]
    buildSchema
        "transcendental_argument"
        "Ask what must already exist for an undeniable fact or behavior to be possible."
        "When a capability clearly works and you need preconditions (replay, caps, review)."
        [ reqStr "undeniable_fact" "Fact hard to dispute (tests pass, plugin loads, message replays)."
          reqArr "necessary_preconditions" 3 "Structures that must exist (event log, ToolSpec SSOT, Fable compile)."
          reqStr "dependency_chain" "How preconditions enable the fact."
          reqArr "missing_precondition_tests" 1 "What would break if a precondition were removed."
          optStr "philosophical_limit" "What this argument does not prove (implementation detail)."
          optArr "engineering_implications" 2 "What not to delete in refactor." ]
        "Reverse-engineer prerequisites from stable facts."
        [ "Undeniable fact"
          "Precondition chain"
          "Break tests"
          "Implications"
          "Next actions" ]
]
