module Wanxiangshu.Methodology.Catalog3

open Wanxiangshu.Methodology.SchemaCommon

let entries: MethodologyEntry list = [
    { methodologyId = "dynamic_programming"
      shortDefinition = "Exploit overlapping subproblems and optimal substructure with memoized state transitions."
      triggerWhen = "When repeated subtasks appear (schema gen per tool, replay segments, fuzzy pages)."
      noteDescription = "top_level_goal, subproblems, overlap_evidence, state_definition, transitions, memoization_plan, base_cases, complexity_note"
      meditatorRole = "Factor overlapping work into memoized states appropriate for vibe-fs stores."
      outputSections = [ "Subproblem decomposition"; "State and transitions"; "Memoization"; "Next actions" ] }
    { methodologyId = "monte_carlo_sampling"
      shortDefinition = "Sample plausible paths when space is too large; verify critical findings deterministically."
      triggerWhen = "When exhaustive reasoning over sessions, tool combos, or message orderings is infeasible."
      noteDescription = "decision_question, sample_space, samples_drawn, stability_signal, deterministic_followups, sample_size_rationale, outliers"
      meditatorRole = "Sample cheaply then nail truth with deterministic verification."
      outputSections = [ "Sampling plan"; "Stable signal"; "Outliers"; "Deterministic followups"; "Next actions" ] }
    { methodologyId = "simulated_annealing"
      shortDefinition = "Accept worse interim states early to escape local optima; cool into refinement."
      triggerWhen = "When greedy refactor or fix order gets stuck in a local minimum."
      noteDescription = "objective_function, current_state, neighbor_moves, acceptance_policy, cooling_schedule, best_so_far, termination"
      meditatorRole = "Plan exploration vs exploitation when incremental edits plateau."
      outputSections = [ "Objective"; "Neighbor moves"; "Annealing schedule"; "Commit criteria"; "Next actions" ] }
    { methodologyId = "swarm_optimization"
      shortDefinition = "Parallel candidate directions explore, share best findings, converge without early overcommit."
      triggerWhen = "When multiple subagents, hypotheses, or design drafts can search in parallel."
      noteDescription = "collective_goal, agents_or_hypotheses, share_mechanism, diversity_rules, convergence_criteria, best_candidate, retired_candidates"
      meditatorRole = "Orchestrate parallel exploration with explicit merge and convergence rules."
      outputSections = [ "Swarm layout"; "Sharing protocol"; "Convergence"; "Leader candidate"; "Next actions" ] }
    { methodologyId = "systems_thinking"
      shortDefinition = "Model feedback loops, dependencies, delays, and emergent behavior."
      triggerWhen = "When a change in hooks, tools, or prompts ripples through sessions and review loops."
      noteDescription = "system_boundary, stocks, flows, feedback_loops, delays, emergent_risk, leverage_points, simulation_or_trace"
      meditatorRole = "Draw loops and delays so host-side tweaks are not judged in isolation."
      outputSections = [ "Stock-flow sketch"; "Feedback loops"; "Delays"; "Leverage points"; "Next actions" ] }
    { methodologyId = "root_cause_analysis"
      shortDefinition = "Trace symptoms to causal fault, not visible failure only."
      triggerWhen = "When repeated failures, flaky tests, or incident-like tool errors need depth."
      noteDescription = "symptom, visible_failure, why_chain, root_cause, contributing_factors, fix_target, verification_after_fix, symptom_vs_cause_guard"
      meditatorRole = "Drive why-chain to an actionable root with verification, not patch-the-symptom."
      outputSections = [ "Symptom vs visible failure"; "Why chain"; "Root cause"; "Fix target"; "Verification"; "Next actions" ] }
    { methodologyId = "state_machine_reasoning"
      shortDefinition = "Enumerate legal states, transitions, and impossible states."
      triggerWhen = "When behavior is modal: review, nudge, KG job, todo in_progress discipline."
      noteDescription = "machine_name, states, transitions, illegal_states, current_state_guess, missing_transitions, exhaustiveness_check"
      meditatorRole = "Make FSM explicit and align implementation with illegal state elimination."
      outputSections = [ "State list"; "Transition table"; "Illegal states"; "Gap analysis"; "Next actions" ] }
    { methodologyId = "type_driven_design"
      shortDefinition = "Encode domain boundaries and illegal states in types."
      triggerWhen = "Before implementing hooks or tools still passing Dyn obj through business logic."
      noteDescription = "domain_slice, illegal_states_today, algebraic_model, encoding_plan, operations_as_functions, compiler_guarantees, migration_from_dyn"
      meditatorRole = "Design types so illegal states are unwritable before coding handlers."
      outputSections = [ "Illegal state inventory"; "Algebraic model"; "Codec boundary"; "Migration steps"; "Next actions" ] }
    { methodologyId = "event_sourcing"
      shortDefinition = "Separate commands from facts; derive current state from event history."
      triggerWhen = "When mutable maps disagree with message history or replay is required."
      noteDescription = "command_side, event_side, events_list, fold_function, replay_requirements, snapshot_policy, correction_events, anti_patterns"
      meditatorRole = "Align command/event split with history-as-truth discipline in vibe-fs."
      outputSections = [ "Command vs event"; "Event catalog"; "Fold/replay"; "Correction strategy"; "Next actions" ] }
    { methodologyId = "operationalism"
      shortDefinition = "Define concepts by observable operations that detect or change them; discard non-behavioral distinctions."
      triggerWhen = "When vague terms (done, stable, registered) need testable meaning."
      noteDescription = "vague_term, observation_operations, mutation_operations, equivalence_criterion, discarded_distinctions, operational_spec, counterexamples"
      meditatorRole = "Replace metaphysical labels with observation/mutation specs."
      outputSections = [ "Term under scrutiny"; "Operational definition"; "Discarded distinctions"; "Implementable spec"; "Next actions" ] }
    { methodologyId = "bayesian_update"
      shortDefinition = "Update belief strength as evidence arrives; avoid all-or-nothing after one test."
      triggerWhen = "When multiple hypotheses compete (host bug vs kernel bug vs stale build)."
      noteDescription = "hypothesis_set, prior_weights, new_evidence, likelihood_sketch, posterior_summary, decisive_experiment, discarded_hypotheses"
      meditatorRole = "Qualitative Bayesian update over competing engineering hypotheses."
      outputSections = [ "Priors"; "Evidence"; "Likelihood notes"; "Posterior"; "Decisive experiment"; "Next actions" ] }
    { methodologyId = "falsification"
      shortDefinition = "Formulate hypotheses with clear failure conditions; search counterexamples."
      triggerWhen = "When a design claim risks becoming unfalsifiable narrative."
      noteDescription = "claim, failure_conditions, search_attempts, verdict, surviving_scope, popper_note, new_tests"
      meditatorRole = "Try to kill the claim before shipping it."
      outputSections = [ "Claim"; "Failure conditions"; "Search log"; "Verdict and revised scope"; "Next actions" ] }
    { methodologyId = "thought_experiment"
      shortDefinition = "Push idealized or extreme scenarios through rules to test concept boundaries."
      triggerWhen = "When real execution is costly or dangerous (data loss, prod hook, oversized payloads)."
      noteDescription = "scenario_setup, rule_under_test, scenario_steps, derived_outcome, boundary_insights, mapping_to_real, real_tests_inspired"
      meditatorRole = "Stress rules in imagination before paying execution cost."
      outputSections = [ "Scenario"; "Steps"; "Outcome"; "Insights"; "Inspired tests"; "Next actions" ] }
    { methodologyId = "transcendental_argument"
      shortDefinition = "Ask what must already exist for an undeniable fact or behavior to be possible."
      triggerWhen = "When a capability clearly works and you need preconditions (replay, caps, review)."
      noteDescription = "undeniable_fact, necessary_preconditions, dependency_chain, missing_precondition_tests, philosophical_limit, engineering_implications"
      meditatorRole = "Reverse-engineer prerequisites from stable facts."
      outputSections = [ "Undeniable fact"; "Precondition chain"; "Break tests"; "Implications"; "Next actions" ] }
]
