namespace Wanxiangshu.Sphinx.V2.Core

open System

/// The user's original goal, preserved byte for byte, plus every authorized amendment.
///
/// WHAT[sphinx-v2-001]: LLM-generated `GoalInterpretation`, `ReframingProposal` and
/// `MissingConstraint` are ordinary semantic graph nodes. They never touch this
/// record: the original text is a byte-exact copy, and the revision counter only
/// moves under an explicit user `AmendGoal` command. A model that decides the goal
/// really means something else produces a new interpretation node, not a new goal.

type GoalAmendment =
    { AuthorizedBy: string
      Revision: Revision
      AddedConstraints: string list
      ReplacedText: string option }

type GoalSpec =
    { GoalId: GoalId
      Revision: Revision
      /// Byte-exact user text. Never normalized, trimmed or reworded in storage.
      OriginalText: string
      /// Explicit supplementary constraints from the user, as supplied.
      Constraints: string list
      /// Content refs of the material the user attached; may be empty.
      MaterialRefs: ArtifactRef list
      /// Authorization reference proving the user supplied this goal.
      AuthorizationRef: string
      CreatedBy: string
      Amendments: GoalAmendment list }

type GoalError = { Code: string; Message: string }

module Goal =

    /// Text is kept verbatim, so a surrounding newline is a real difference the user
    /// typed. Only total emptiness is rejected, and a controller-supplied plain-text
    /// authorization is required so the goal cannot be auto-generated by a plugin.
    let private validate (goal: GoalSpec) : Result<unit, GoalError> =
        if String.IsNullOrWhiteSpace goal.OriginalText then
            Error
                { Code = "invalid-goal"
                  Message = "goal text must not be blank" }
        elif String.IsNullOrWhiteSpace goal.AuthorizationRef then
            Error
                { Code = "invalid-goal"
                  Message = "goal requires a user authorization reference" }
        elif
            goal.Amendments
            |> List.exists (fun amendment -> Revision.value amendment.Revision > Revision.value goal.Revision)
        then
            Error
                { Code = "invalid-goal"
                  Message = "amendment revision cannot exceed the goal revision" }
        else
            Ok()

    let tryCreate (goal: GoalSpec) : Result<GoalSpec, GoalError> = validate goal |> Result.map (fun () -> goal)

    let create (goal: GoalSpec) : GoalSpec =
        match tryCreate goal with
        | Ok created -> created
        | Error message -> invalidArg (nameof goal) message.Message

    /// The only way the goal advances. Returns the next revision and keeps the
    /// original text byte-exact; `ReplacedText` is the user's own replacement, not a
    /// proposal accepted on their behalf.
    let amend
        (authorizedBy: string)
        (addedConstraints: string list)
        (replacementText: string option)
        (goal: GoalSpec)
        : GoalSpec =
        let revision = Revision.next goal.Revision

        { goal with
            Revision = revision
            OriginalText = defaultArg replacementText goal.OriginalText
            Constraints = goal.Constraints @ addedConstraints
            Amendments =
                goal.Amendments
                @ [ { AuthorizedBy = authorizedBy
                      Revision = revision
                      AddedConstraints = addedConstraints
                      ReplacedText = replacementText } ] }

    /// An amendment that must at least name its author and not be blank.
    let tryAmend
        (authorizedBy: string)
        (addedConstraints: string list)
        (replacementText: string option)
        (goal: GoalSpec)
        : Result<GoalSpec, GoalError> =
        if String.IsNullOrWhiteSpace authorizedBy then
            Error
                { Code = "invalid-goal"
                  Message = "goal amendment requires a non-blank authorizer" }
        else
            let amended = amend authorizedBy addedConstraints replacementText goal
            validate amended |> Result.map (fun () -> amended)
